Sprint6-138063171-2  locale entries
AgileVentures/shf-project pull request #128
Opened 2017-01-23 23:48 UTC by weedySeaDragon

part 2: Entries for locale files

**Depends on PR #127 (part 1 for this PT story)**

NEED BETTER TRANSLATIONS for .sv entries

(This is the second PR for the PT story below.)

PT Story: Delete company associated with deleted membership application. (see details)
#138063171 https://www.pivotaltracker.com/story/show/138063171

Changes proposed in this pull request:
1. added entries to .sv and .en locale files

Ready for review:
@thesuss

2017-01-24 12:43 UTC, thesuss requested changes

2017-01-24 12:43 UTC, thesuss commented on config/locales/sv.yml
> +          company_has_active_memberships: "NEEDS TRANSLATION The company has active (accepted) membership applications."
Företaget har aktiva (godkända) medlemskap.

2017-01-24 12:43 UTC, thesuss commented on config/locales/sv.yml
> +      delete: "Radera företaget NEEDS TRANSLATION REVIEW"
Radera
- should be enough?

2017-01-24 12:43 UTC, thesuss commented on config/locales/sv.yml
> +      success: Företag raderad.
Företaget raderat.

2017-01-24 12:43 UTC, thesuss commented on config/locales/sv.yml
> +      error: TRANSLATION NEEDED Ett problem hindrade företaget från att raderas.
Ett problem hindrade företaget från att raderas.
- is fine

2017-01-24 19:44 UTC, weedySeaDragon commented
changes made, @thesuss !

2017-01-27 19:40 UTC, thesuss approved these changes

2017-01-27 19:41 UTC, merged