[WIP] View and show incoming applications as admin
AgileVentures/shf-project pull request #13
Opened 2016-11-11 18:38 UTC by thesuss

PT Story: 
https://www.pivotaltracker.com/story/show/133950343

Changes proposed in this pull request:
1. Index view for memberships
2. Show page for memberships
3.

2016-11-11 19:20 UTC, tochman requested changes

2016-11-11 19:20 UTC, tochman commented on features/show_membership_application.feature
> +
I suggest we include a link to the PT story in the feature.

2016-11-11 19:20 UTC, tochman commented on features/show_membership_application.feature
> +  And I should see "din@mail.se"
Plz mind the code formatting

2016-11-11 19:20 UTC, tochman commented on features/show_membership_application.feature
> +  And I should see "Tassa-in AB"
Perhaps it would be enough to say `I see "3" applications"`?

2016-11-11 19:20 UTC, tochman commented on features/step_definitions/application_steps.rb
> +    MembershipApplication.create application
FactoryGirl is installed and there is a `:membership_application` factory. I suggest you use that.

2016-11-11 19:20 UTC, tochman commented on features/step_definitions/navigation_steps.rb
> +  @membership = MembershipApplication.find_by(company_name: name)
A local variable will do. No need to store the MembershipApplication in an instance variable.

2016-11-11 19:20 UTC, tochman commented on features/step_definitions/navigation_steps.rb
> +Then(/^I should be on "([^"]*)" page$/) do |name|
This step definition feels a bit vague.

2016-11-11 19:20 UTC, tochman commented on features/show_membership_application.feature
> +  Then I should be on "DoggieZone" page
See comment below. IMO this step definition does not reflect where the user actually ends up.

2016-11-11 19:21 UTC, thesuss commented on features/show_membership_application.feature
> +
Okay

2016-11-11 19:21 UTC, thesuss commented on features/show_membership_application.feature
> +  And I should see "Tassa-in AB"
Ah, I will try that

2016-11-11 19:29 UTC, thesuss commented on features/step_definitions/application_steps.rb
> +    MembershipApplication.create application
Yes

2016-11-11 19:29 UTC, thesuss commented on features/show_membership_application.feature
> +  And I should see "din@mail.se"
Use tables instead?

2016-11-11 19:30 UTC, thesuss commented on features/step_definitions/navigation_steps.rb
> +Then(/^I should be on "([^"]*)" page$/) do |name|
In what way?

2016-11-11 20:14 UTC, tochman commented on features/show_membership_application.feature
> +  And I should see "din@mail.se"
No, I mean code indentation

2016-11-11 20:19 UTC, thesuss commented on features/show_membership_application.feature
> +  And I should see "din@mail.se"
ah, fixed

2016-11-11 20:19 UTC, tochman requested changes

2016-11-11 20:19 UTC, tochman commented on app/views/memberships/index.html.haml
> +  - @membership.each do | info |
Just spotted this.This is a collection, right?  Should be in plural: `@memberships`or better yes `@membership_applications` or `@applications`

2016-11-11 20:19 UTC, tochman commented on features/create_membership_application.feature
> +      | Craft Academy | 1234561234     | Thomas         | info@craft.se | 031-1234567  |
This refactoring is okay but out of scope for this PR

2016-11-11 20:19 UTC, tochman commented on features/show_membership_application.feature
> +  | din@mail.se   |
Mind code formatting/indentation in this file

2016-11-11 20:19 UTC, tochman commented on features/step_definitions/application_steps.rb
> +Then(/^I should see "([^"]*)" applications$/) do |number|
Try to have a line break between step defs for better readability

2016-11-11 20:41 UTC, tochman commented
Staying in scope is important for many reasons. The changes in  `create_membership_application.feature` will create a situation where the team will have to deal with merging conflicts. PR https://github.com/AgileVentures/shf-project/pull/15 introduces a relation between a new User class and MembershipApplication, meaning that the `create_membership_application.feature` will be affected. Not a big deal but we all know what many merge conflicts can lead to.

2016-11-11 20:42 UTC, tochman commented on app/views/memberships/index.html.haml
> +  - @membership_applications.each do | info |
Okay, so `info` is what exactly? An instance of MembershipApplication, right?

2016-11-11 20:51 UTC, tochman commented on features/step_definitions/navigation_steps.rb
> +Then(/^I should be on "([^"]*)" page$/) do |company_name|
Okay, so IMO `I should be on "Whatever Business Name" page` does not reflect that I am seeing the application for "Whatever Business Name". It can be anything. A profile page, a directory listing, etc. My point is that the step definition should be descriptive.

2016-11-11 20:52 UTC, tochman commented on features/step_definitions/navigation_steps.rb
> +Then(/^I should be on "([^"]*)" page$/) do |company_name|
But the refactoring of the variable name to `company_name` was a good move ;-)

2016-11-11 20:57 UTC, thesuss commented
I stayed in scope and did 
https://www.pivotaltracker.com/story/show/134192313

2016-11-11 21:00 UTC, thesuss commented on features/step_definitions/navigation_steps.rb
> +Then(/^I should be on "([^"]*)" page$/) do |company_name|
I do see what you mean. I'm sure your PR will have that type of steps so if this one gets merged it will be refactored along those lines. With a case statement and a "goto" or similar.

2016-11-11 21:01 UTC, tochman commented
One PR per feature/chore should be a guideline. Creating Chores on the fly does not work in a team collaboration. I'm sorry if I come across as unreasonable but I see an upcoming mess when it comes to merge the code.

2016-11-11 21:11 UTC, thesuss commented
I created the chore so we would not forget to do it later on, since it's now not done in this PR

2016-11-11 21:11 UTC, tochman commented
And if I was sure that other members could resolve those merge conflicts I would rest my case. But for now I'm inclined to ask you to remove commits dealing with the newly created Chore

2016-11-11 21:11 UTC, tochman approved these changes

2016-11-11 21:12 UTC, tochman commented
Okay, now I understand.

2016-11-12 14:42 UTC, diraulo approved these changes

2016-11-12 14:57 UTC, merged