add public/storage to list of folder to symlink after deployment
AgileVentures/shf-project pull request #134
Opened 2017-01-29 20:55 UTC by diraulo

PT Story: https://www.pivotaltracker.com/story/show/138558657

Changes proposed in this pull request:
1. Add `public/storage` directory to Capistrano's list of `linked_dirs`. All directories that are common to every deployment must be created in the `shared` directory in production (DO) and added to this list. After every deployment Capistrano creates a symlink of the linked_dirs into the current release

I created the `storage` directory already on the server and restored files from the previous release. In principle, all missing images should be restored now.

Ready for review:
@thesuss @weedySeaDragon @patmbolger

2017-01-29 21:15 UTC, weedySeaDragon requested changes
This is the right directory to add.

But since files have been uploaded for more than just the most recent release, we need files from /storage/.... restored from _all_ previous releases.

2017-01-30 07:52 UTC, thesuss commented
@weedySeaDragon  He says "I created the storage directory already on the server and restored files from the previous releases. In principle, all missing images should be restored now."

2017-01-30 07:54 UTC, thesuss approved these changes

2017-01-30 08:36 UTC, weedySeaDragon commented
I misread that.  I just saw 'previous release' (singular).  Glad I was wrong. :-)

2017-01-30 08:36 UTC, weedySeaDragon approved these changes

2017-01-30 08:51 UTC, merged