Toggle Hide/Show search form #138068115
AgileVentures/shf-project pull request #135
Opened 2017-01-29 21:41 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/138068115

Changes proposed in this pull request:
1. Add control to companies index view to hide / show search form
2. Add Gen ```i18n-js``` for i18n functionality (via Rails config) in client
3. Add JS method to toggle visibility of an element
4. Add embedded script to layout view to set i18n default and current locale in client (when  user changes locale / language)
5. Add feature test for toggle 

Screenshots (Optional):
<hr>
<img width="733" alt="screen shot 2017-01-29 at 4 38 41 pm" src="https://cloud.githubusercontent.com/assets/9968213/22408138/8f9800c2-e641-11e6-89ef-b89289888364.png">

<hr>
<img width="776" alt="screen shot 2017-01-29 at 4 39 02 pm" src="https://cloud.githubusercontent.com/assets/9968213/22408141/960c9008-e641-11e6-8ad3-ebd18a15e085.png">

<hr>
<img width="720" alt="screen shot 2017-01-29 at 4 39 13 pm" src="https://cloud.githubusercontent.com/assets/9968213/22408143/9aaff0a0-e641-11e6-81e8-f01075c7580a.png">

<hr>
<img width="719" alt="screen shot 2017-01-29 at 4 39 24 pm" src="https://cloud.githubusercontent.com/assets/9968213/22408144/9f1c4b5c-e641-11e6-9b25-292557889ef4.png">

Ready for review:
@thesuss @weedySeaDragon

2017-01-30 08:28 UTC, thesuss commented on config/locales/sv.yml
> +    hide: Dölja
Dölj 

(Dölja = to hide)

2017-01-30 08:30 UTC, thesuss commented
```
    Then I wait for 1 second                                                              # features/step_definitions/basic_steps.rb:103
    Then I select "Groomer" in select list t("activerecord.models.business_category.one") # features/step_definitions/basic_steps.rb:98
      Unable to find select box "Kategori" (Capybara::ElementNotFound)
      ./features/step_definitions/basic_steps.rb:100:in `/^(?:I|they) select "([^"]*)" in select list t\("([^"]*)"\)$/'
      features/search_companies.feature:53:in `Then I select "Groomer" in select list t("activerecord.models.business_category.one")'
```

Maybe wait longer?

2017-02-01 21:27 UTC, diraulo approved these changes
The build is all good now. Sorry but didn't get a chance to look at this earlier. All that was missing was the setting @patmbolger suggested and @thesuss has access to Semaphore so you could've made that change too 😉 

We should probably move this project to the AV org at some point, that'll give members of the teams access to modify the build settings as necessary in future.

Also, you might want to consider an alternative way of including external dependencies (JS libraries, etc.. ) they're hurting your GPA on codeclimate so badly.

2017-02-01 22:31 UTC, diraulo reviewed
@patmbolger now that you have the `i18n-js` gem in place do you still need `public/javascripts/i18n.js`?

I think you can just add `= require i18n.js` and remove the file in the js folder.

2017-02-01 22:31 UTC, diraulo commented on Gemfile
> +gem 'i18n-js', '>= 3.0.0.rc11'
👍

2017-02-01 22:41 UTC, patmbolger commented on Gemfile
> +gem 'i18n-js', '>= 3.0.0.rc11'
@diraulo - thanks, I'll try that.

2017-02-02 19:29 UTC, weedySeaDragon requested changes
Looking good. (and all tests pass on my machine.  hooray!)

1 change that needs to be made to en.yml, and these UX suggestions (which could be done in a different PR):

1. I don't think `(Show)` and `(Hide)` are clear enough.  I don't think they communicate that they are connected to the search form.  I'd rather see something like:

    `Search for companies using the search form. (Show the search form.)`

   and 

    `...     (Hide the search form.)`

    And include an icon to for the 'show/expand' and 'hide/collapse' idea as well. Maybe a down triangle and up triangle.



2. The search form disappears when the results are displayed.  We need some visual indicator/cue that what the user is seeing is the result of a search with some criteria/filters.  Either don't hide the search form or show the criteria somehow.

2017-02-02 19:29 UTC, weedySeaDragon commented on config/locales/en.yml
> +      how_to_search: Search for companies in search form.
grammar fix: need `the`

`how_to_search: Search for companies in the search form.`

or something a little more explicit (_using..._):

`Search for companies using the search form.`

2017-02-03 10:23 UTC, patmbolger commented
Thanks for the review @weedySeaDragon 

I changed the wording on the search form along the lines of your suggestions.

Regarding your second comment, I added this chore: https://www.pivotaltracker.com/story/show/139001697

2017-02-03 10:54 UTC, thesuss requested changes

2017-02-03 10:54 UTC, thesuss commented on config/locales/sv.yml
> +      hide: Dölja sökfunktionen
Dölj sökfunktionen 
(no a)

2017-02-03 10:54 UTC, thesuss commented on config/locales/sv.yml
> +      how_to_search: Sök efter företag som använder sökfunktionen.
Sök efter företag genom att använda sökfunktionen.

2017-02-03 11:45 UTC, thesuss approved these changes

2017-02-03 13:41 UTC, weedySeaDragon approved these changes

2017-02-03 21:05 UTC, merged