Members get Newsletter: download emails to csv (commits are cleaned up)
AgileVentures/shf-project pull request #136
Opened 2017-01-30 21:14 UTC by weedySeaDragon

PT Story: **Members get Newsletter: download emails to csv**
https://www.pivotaltracker.com/story/show/133081751

_Note: this replaces PR #131 .  The commits in that PR got messed up.  I've rebased and so the commits are fixed._

Dump all membership applications to .csv so the user's browser can download it.
- I also included the membership status; I made a leap and assumed it would be helpful since _all_ of the membership applications are being dumped.
- The headers and each membership_application state is translated as appropriate

Changes proposed in this pull request:
1.  added 'Export...' button on the **admin root page** (_not_ the membership_applications index) because the admin root page has additional security provided in routes
2. added 'export_ankosan_csv' action to AdminController
3. added AdminPolicy
4. added locale file entries -- **Swedish entries need translating!!!**
5. specs for AdminContoller and AdminPolicy
6. feature for export-member-email-info
7. added index on `state` for `membership_applications`

(There are more commits than there need be because I noodled around with exporting from MembershipApplication first.)

**Screenshots (Optional):**
![screenshot-export-ankosan-csv-sv](https://cloud.githubusercontent.com/assets/673794/22276840/6ba25aac-e26b-11e6-9a9d-53fd4d1fd3d7.png)

![screenshot-export-ankosan-csv-en](https://cloud.githubusercontent.com/assets/673794/22276839/6b9f69fa-e26b-11e6-9f50-3c75ed3031cf.png)

Ready for review:
@thesuss @patmbolger

2017-02-03 10:48 UTC, thesuss requested changes

2017-02-03 10:48 UTC, thesuss commented on config/locales/sv.yml
> +      new: &status_new Nytt
Whether its "Ny" or "Nytt" depends on what specifically it is that is new. 
Ansökan ends with "n" therefore wording should be "Ny"

2017-02-03 10:48 UTC, thesuss commented on config/locales/sv.yml
> +      export: Export all applications to a CSV file
Exportera ansökningar som CSV

2017-02-03 10:48 UTC, thesuss commented on config/locales/sv.yml
> +      success: Export successful. Check your browser downloads for the file.
Exporten lyckades. Du hittar filen bland din webbläsares nedladdade filer.

2017-02-03 10:48 UTC, thesuss commented on config/locales/sv.yml
> +      error: There was a problem with the export.
Ett problem uppstod med exporten.

2017-02-03 10:48 UTC, thesuss commented on config/locales/sv.yml
>      start_review: &start_review Starta omdöme
Påbörja granskning

2017-02-03 21:06 UTC, thesuss commented on config/locales/sv.yml
>      start_review: &start_review Starta omdöme
It seems you missed one?

2017-02-03 21:10 UTC, thesuss requested changes

2017-02-03 21:10 UTC, thesuss commented on config/locales/sv.yml
> +      ready_for_review: &status_ready_for_review Påbörja granskning
Redo för granskning

2017-02-05 01:58 UTC, weedySeaDragon commented on config/locales/sv.yml
>      start_review: &start_review Starta omdöme
@thesuss I've got it now.  If you agree, then can you merge this so it'll be ready to demo Sunday?

2017-02-05 18:24 UTC, merged