removed old_region from company #139602987
AgileVentures/shf-project pull request #160
Opened 2017-02-21 12:30 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/139602987

Changes proposed in this pull request:
1. Removed `old_region` attribute from Company model
2. Adjusted prod and test code
3. Adjusted rake task

Ready for review:
@weedySeaDragon 
@thesuss

2017-02-21 18:37 UTC, weedySeaDragon requested changes
2 minor questions and a suggestion.

2017-02-21 18:37 UTC, weedySeaDragon commented on app/models/company.rb
>    def complete?
This method is no longer used anywhere.  Should we delete it?

2017-02-21 18:37 UTC, weedySeaDragon commented on app/helpers/companies_helper.rb
> +    return false if ! company
I'm not sure this is used anywhere.  When I did a search in the code for `company_complete?`  I only found it being used in the specs and features.

We now only return `complete` companies from the database so there's no need to filter them in the views (via a helper).  So perhaps we can remove this method altogether?

If we do keep it, what about changing this to:

```
company.nil? ? false : company.complete?
```

2017-02-21 21:50 UTC, patmbolger commented on app/helpers/companies_helper.rb
> +    return false if ! company
You're right about both methods.

The only reason I might think to retain these is that I imagine in the future we'll be asked to create a view showing _all_ companies, regardless of "complete" status.  For instance, to allow for deleting abandoned efforts to create a company (which are cluttering up the DB with useless records).

However, that is not an argument to retain these methods.  We can cross that bridge when we come to it.  (should have given a cliché trigger warning ...)

I will remove the two methods.

2017-02-22 01:27 UTC, weedySeaDragon approved these changes

2017-02-22 13:34 UTC, merged