show open apps in users view #140598375
AgileVentures/shf-project pull request #166
Opened 2017-02-24 22:05 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/140598375

Changes proposed in this pull request:
1. Show only "open" (not accepted, not rejected) applications count in users index view  (requested by client after review of User index view)

Screenshots (Optional):

Ready for review:
@weedySeaDragon 
@thesuss

2017-02-25 20:05 UTC, weedySeaDragon approved these changes
Nice thought to do the tooltip. 👍

2017-03-02 01:13 UTC, weedySeaDragon commented
@thesuss is the `sv.yml` OK?  If so, we can merge it

2017-03-02 12:36 UTC, thesuss requested changes

2017-03-02 12:36 UTC, thesuss commented on config/locales/sv.yml
> +      applications_tooltip: Antal öppna program
Lol..... 
      applications: Ansökningar
      applications_tooltip: Antal öppna program

*** 

      applications: Ansökningar
      applications_tooltip: Antal öppna **ansökningar**

2017-03-03 07:57 UTC, thesuss approved these changes

2017-03-03 08:11 UTC, merged