Create separate Address class; move data out of Company class
AgileVentures/shf-project pull request #169
Opened 2017-03-01 18:13 UTC by weedySeaDragon

PT Story: Create an "Address" class; refactor out of company
https://www.pivotaltracker.com/story/show/140192663

This is the first

Note that I do _not_ remove the address-related columns out of the `companies` table in the db because we need to make sure that the current data is migrated out into the new `addresses` table first.  (I created the `shf:move_company_addresses_to_addresses` task for this.)

Changes proposed in this pull request:
1.  create the Address class (and associated addresses db table)
2. update `db:seed`
3. added a rake task to migrate the data
2. update specs and features
3. update CompanyController to load addresses for each company as appropriate
4. update views

Ready for review:
@patmbolger @thesuss

2017-03-03 08:23 UTC, thesuss commented on config/locales/en.yml
> +        region: &region Region
Where is this used?

2017-03-03 08:24 UTC, thesuss commented on config/locales/en.yml
> +        region_short: &region_short Län
Where is this used?

2017-03-03 08:25 UTC, thesuss commented on config/locales/en.yml
> +        region: &region Region
Aha this one is "Region of operations"

2017-03-03 08:25 UTC, thesuss commented on config/locales/en.yml
> +        region_short: &region_short Län
And this one is "Region"

2017-03-03 08:26 UTC, thesuss approved these changes
Nothing strange as far as I can see, but more people should have a look :)

2017-03-03 11:09 UTC, patmbolger reviewed
Please see comments

2017-03-03 11:09 UTC, patmbolger commented on app/controllers/companies_controller.rb
> +    @company.addresses.first.addressable = @company  # not sure why Rails doesn't assign this automatically
I think this statement could replace the above two statements:
```
@company.assign_attributes(company_params)
```
It is smarter about associated models when the parent model has `accepts_nested_attributes_for` (which your Company model _does_ have).

2017-03-03 11:09 UTC, patmbolger commented on app/models/company.rb
> +  has_many :addresses, as: :addressable, dependent: :destroy, foreign_key: :addressable_id
Is `foreign_key: :addressable_id` needed?  Should default to that, I think.

2017-03-03 11:09 UTC, patmbolger commented on app/models/company.rb
> +    have_no_regions = Address.lacking_region.distinct.pluck(:addressable_id)
Since `Address` is polymorphic, and ID's can be the same across models (e.g. Company and User), shouldn't this be limited to addresses for companies?  Perhaps something like this:
```
have_no_regions = Address.lacking_region.where(addressable_type: 'Company').distinct.pluck(:addressable_id)
```

2017-03-03 11:09 UTC, patmbolger commented on lib/tasks/shf.rake
> +      co_address.addressable = company
This is a bit obscure(?).  Consider:
```
company.addresses << co_address
```

2017-03-03 11:09 UTC, patmbolger commented on spec/factories/companies.rb
> +      num_adresses 1
`num_addresses`

2017-03-03 11:09 UTC, patmbolger commented on app/views/companies/_companies_list.html.haml
> +          %td= company.addresses.first.city
These statements will fail in production unless the rake task (included in this PR) is run first.  I assume this is the plan(?)

2017-03-03 19:37 UTC, thesuss requested changes
Do not merge until rake task is run in production...

2017-03-03 19:45 UTC, thesuss approved these changes

2017-03-04 23:43 UTC, weedySeaDragon commented on app/models/company.rb
> +    have_no_regions = Address.lacking_region.distinct.pluck(:addressable_id)
Good point.

2017-03-05 00:54 UTC, weedySeaDragon commented on app/controllers/companies_controller.rb
> +    @company.addresses.first.addressable = @company  # not sure why Rails doesn't assign this automatically
I couldn't make that work.  I wonder if it has something to do with the fact that we're dealing with an Array of Addresses for a Company?

2017-03-05 00:55 UTC, weedySeaDragon commented on lib/tasks/shf.rake
> +      co_address.addressable = company
no longer applicable since that code is now deleted (not included in this PR)

2017-03-05 11:34 UTC, patmbolger approved these changes

2017-03-05 11:34 UTC, merged