Create PULL_REQUEST_TEMPLATE.
AgileVentures/shf-project pull request #2
Opened 2016-10-26 15:15 UTC by lollypop27

@diraulo can yo please merge this pr template in. Thanks

2016-10-26 15:20 UTC, thesuss approved these changes
Thanks!

2016-10-26 15:21 UTC, diraulo requested changes
Your filename is missing the extention `.md`

2016-10-26 16:02 UTC, lollypop27 commented
@diraulo thanks for picking that up, I have updated the file extenstion

2016-10-27 12:29 UTC, diraulo approved these changes

2016-10-27 12:30 UTC, merged