Edit member pages #136724739
AgileVentures/shf-project pull request #203
Opened 2017-04-03 20:14 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/136724739

Changes proposed in this pull request:
1. Add ability to edit member (static) pages
2. Ckeditor::Picture class enhanced to accommodate images for member pages (in addition to company images)
3. All member pages converted to HTML (from HAML)

Screenshots (Optional):
<img width="478" alt="screen shot 2017-04-03 at 4 12 16 pm" src="https://cloud.githubusercontent.com/assets/9968213/24629821/6da5cf98-1888-11e7-95d5-dfcabd1ac7b9.png">
---
<img width="847" alt="screen shot 2017-04-03 at 4 12 35 pm" src="https://cloud.githubusercontent.com/assets/9968213/24629838/7853f244-1888-11e7-8e6c-0d53425517b6.png">
---
<img width="767" alt="screen shot 2017-04-03 at 4 12 50 pm" src="https://cloud.githubusercontent.com/assets/9968213/24629845/7d7f3cf6-1888-11e7-8603-e379f8d0ae64.png">

Ready for review:
@weedySeaDragon 
@thesuss

2017-04-04 06:42 UTC, weedySeaDragon requested changes
Nice work, Pat.  
I just saw that 1 little t() that is needed.  Other than that, it looks good.

2017-04-04 06:42 UTC, weedySeaDragon commented on app/views/shf_documents/contents_edit.html.haml
> +    = link_to 'Cancel', contents_show_path(@page),
Needs Iocalization: `t('cancel')`

2017-04-04 12:31 UTC, thesuss commented
Now, how weird is that? 
<img width="591" alt="skarmavbild 2017-04-04 kl 14 31 12 1" src="https://cloud.githubusercontent.com/assets/7266909/24656577/689b1a24-1943-11e7-81b3-21df0eea4d81.png">

2017-04-04 12:33 UTC, thesuss commented on app/controllers/shf_documents_controller.rb
> -  before_action :authorize_shf_doc_class, only: [:index, :new, :create, :historika_meeting_minutes ]
`:historika_meeting_minutes` which I assume is "protokoll" is missing, is it not needed anymore?

2017-04-04 12:35 UTC, thesuss commented on app/views/application/_navigation_member_pages.html.haml
> +  = render partial: 'shf_documents/documents_list',
Isnt this one listing pages? Documents would be pdf's..

2017-04-04 12:37 UTC, thesuss commented on config/locales/en.yml
> +    edit_shf_document_contents: Edit the SHF document contents
This is confusing... 
Page or Document or "minute" ?

2017-04-04 12:38 UTC, thesuss commented on config/locales/sv.yml
> +    new_shf_minutes:  &new_shf_minutes Lägg till mötesprotokoll Document
remove `Document`

2017-04-04 12:38 UTC, thesuss commented on config/locales/sv.yml
> +    edit_shf_document_contents: Redigera SHF dokumentinnehållet
Where is this? You cannot edit a pdf. 
"Redigera sida" ?

2017-04-04 12:39 UTC, thesuss commented on config/locales/sv.yml
> +    missing_special_letters: 'I dokumenttitlar ovan, bokstäverna å, ä och ö visas som a, a och o, respektive.'
lol 

"Vi beklagar, men för tillfället kan systemet inte visa åäö i undersidornas titlar."

2017-04-04 12:51 UTC, patmbolger commented on app/controllers/shf_documents_controller.rb
> -  before_action :authorize_shf_doc_class, only: [:index, :new, :create, :historika_meeting_minutes ]
There was no action by that name so I removed this reference.

2017-04-04 12:53 UTC, patmbolger commented on app/views/application/_navigation_member_pages.html.haml
> +  = render partial: 'shf_documents/documents_list',
This lists 1) the "meeting minutes" link (which goes to the index view of the meeting minutes documents), and 2) all of the static pages with links created by the HighVoltage gem.

2017-04-04 12:54 UTC, patmbolger commented on config/locales/en.yml
> +    edit_shf_document_contents: Edit the SHF document contents
I agree.  I removed "SHF". 

This is used for the button text that appears in the upper-right hand corner when viewing a "static" member page.  (see 2nd screenshot above)

2017-04-04 12:55 UTC, patmbolger commented on config/locales/sv.yml
> +    new_shf_minutes:  &new_shf_minutes Lägg till mötesprotokoll Document
Done

2017-04-04 12:55 UTC, patmbolger commented on config/locales/sv.yml
> +    edit_shf_document_contents: Redigera SHF dokumentinnehållet
See related comment above.

2017-04-04 12:55 UTC, patmbolger commented on config/locales/sv.yml
> +    missing_special_letters: 'I dokumenttitlar ovan, bokstäverna å, ä och ö visas som a, a och o, respektive.'
Fixed.

2017-04-04 13:05 UTC, thesuss commented on app/views/application/_navigation_member_pages.html.haml
> +  = render partial: 'shf_documents/documents_list',
Ah!

2017-04-04 13:07 UTC, thesuss commented on app/views/shf_documents/_documents_list.html.haml
> +      = link_to page.capitalize, contents_show_path(page: page)
Aha, I see now. It just got cleaned up a bit =)

2017-04-05 23:56 UTC, weedySeaDragon approved these changes

2017-04-11 23:14 UTC, weedySeaDragon commented
The build failed due to the intermittent test fails of doing address geocoding.  sometimes the tests return one set of coordinates, sometimes another.  It almost seems like sometimes it's calling the Google maps API, but sometimes it's getting coordinates another way. (E.g. if you loaded google maps on your browser and did a lookup).  Hmmm.

2017-04-14 19:45 UTC, merged