[WIP] 161114 application status refactor to use policy
AgileVentures/shf-project pull request #24
Opened 2016-11-15 07:55 UTC by weedySeaDragon

PT Story:  **refactor 'Admin reviews application' to use Pundit policy for status** 
https://www.pivotaltracker.com/story/show/134291433

_This PR depends on PR #22  because it refactors/builds on it_ 

Changes proposed in this pull request:
1.  Use the MembershipApplicationPolicy to control who can edit the status
2. create a partial for editing the status (just pulled the existing form into a partial)
3. Simplified the status and timestamp (just downcase the status and add on the timestamp)

Will not be ready for review until PR #22 is merged

2016-11-15 08:17 UTC, thesuss commented on app/views/membership_applications/show.html.haml
> +    - if policy(@membership_application).permitted_attributes_for_edit.include? :status
You can move this line before .wpcf
and put .wpcf in top of the new partial

2016-11-15 09:12 UTC, thesuss approved these changes
I think I understand how the policies work, thanks to the comments. Perhaps they should be removed before merge though?

2016-11-15 11:35 UTC, tochman requested changes

2016-11-15 11:35 UTC, tochman commented on app/controllers/membership_applications_controller.rb
> +    @membership_application = current_user.membership_applications.new
Unless this code is WIP I would like to ask you to remove comments from the code.

2016-11-15 11:35 UTC, tochman commented on app/controllers/membership_applications_controller.rb
> +
I don't think this is necessary. You could probably authorize the class directly by calling 
```
authorize MembershipApplication
```
I think I didi it on the MembershipApplicationController#index

2016-11-15 11:35 UTC, tochman commented on app/policies/membership_application_policy.rb
> +  # When a user creates a MembershipApplication, the status is initialized (so can create it)
Your tests are documenting you code. So comments are not necessary. ;-)

2016-11-15 11:35 UTC, tochman commented on app/views/membership_applications/show.html.haml
> +      = render :partial => 'application_status_form'
Old hash syntax

2016-11-15 11:35 UTC, tochman commented on app/views/membership_applications/show.html.haml
> +    - if policy(@membership_application).permitted_attributes_for_edit.include? :status
It feels like a bit too much logic for a view but IF  there's no other way to do this I'm okay with it. Extract this to a helper perhaps?

2016-11-15 11:35 UTC, tochman commented on app/views/membership_applications/show.html.haml
> +    %p Membership #{@membership_application.status.downcase} at #{@membership_application.updated_at.strftime('%F')}
I would extract this to separate helpers.

2016-11-15 11:35 UTC, tochman commented on spec/policies/membership_application_policy_spec.rb
> +  subject { MembershipApplicationPolicy.new(application_owner, application) }
You are using `described_class` in other parts of the test. Why `MembershipApplicationPolicy` here?

2016-11-15 11:47 UTC, thesuss commented on app/views/membership_applications/show.html.haml
> +      = render :partial => 'application_status_form'
`render partial: 'application_status_form'`

2016-11-15 16:07 UTC, weedySeaDragon commented on spec/policies/membership_application_policy_spec.rb
> +  subject { MembershipApplicationPolicy.new(application_owner, application) }
just sloppiness :-)

2016-11-15 16:16 UTC, weedySeaDragon commented on app/views/membership_applications/show.html.haml
> +    - if policy(@membership_application).permitted_attributes_for_edit.include? :status
agreed.  The `- if...` seems much too heavy since it invokes the policy.

2016-11-16 06:21 UTC, weedySeaDragon commented
Fixed the items noted.

In finding a way to check the parameters during a create (= pass in the class to the policy instead of an instance), I had to do much more fine-grained testing.  (Which is a good thing!)  So the RSpec tests are much more fine-grained now.

2016-11-16 10:29 UTC, tochman requested changes

2016-11-16 10:29 UTC, tochman commented on spec/policies/membership_application_policy_spec.rb
> +      end
In this `it` block you are creating two objects but you have no assertion/expectations. What are you testing. (This goes for the it-blocks below as well)

2016-11-16 10:46 UTC, thesuss commented on spec/policies/membership_application_policy_spec.rb
> +      end
I understand it like they are referenced here. They really are above. Line 32?

2016-11-16 14:12 UTC, weedySeaDragon commented on spec/policies/membership_application_policy_spec.rb
> +      end
This uses the shared example to test that the application owner can see the 'status' attribute.  Given the application, it tests that if the user is the application owner, the user (application owner) can see the _status_ parameter, according to the policy.
 
This it block (and others) uses these `let` statements to set the variables that are used in the shared example.  

Is that what you're asking?

2016-11-16 22:08 UTC, weedySeaDragon commented on spec/policies/membership_application_policy_spec.rb
> +      end
And if it's not clear (kind of aside from the question of _is this the right thing and is it correct_), is there something I can do to make it more clear?

2016-11-17 15:42 UTC, tochman commented on spec/policies/membership_application_policy_spec.rb
> +      end
Okay, I think that this introduces too much complexity to these specs but I can follow the logic. Using shared examples is an interesting approach that I would like to make sure that everybody is onboard with before  we start introducing. I totally see the need to keep specs DRY, but I think it's a bit to early. I will not consider it a blocker though.

2016-11-17 15:42 UTC, tochman approved these changes

2016-11-17 16:39 UTC, weedySeaDragon commented on spec/policies/membership_application_policy_spec.rb
> +      end
I have not problem changing these to not use shared_examples.  I think that RSpec's shared_examples can be unclear; they make the narrative (wording) awkward.  
This is a good example:  this didn't read smoothly and come across clearly to you.

We can merge this so things keep moving forward.  I'll add a chore in PT to refactor and reference this discussion.

2016-11-17 18:33 UTC, merged