added task add_member_page
AgileVentures/shf-project pull request #264
Opened 2017-06-05 15:29 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/145192549

Changes proposed in this pull request:
1. Add task to create a new (empty) file for a new member (static) page

Screenshots (Optional):
### Current Member Page list:
<img width="450" alt="screen shot 2017-06-05 at 11 23 26 am" src="https://cloud.githubusercontent.com/assets/9968213/26790400/93f7ed90-49e1-11e7-91fa-d3588938b341.png">

### Create new member page file:
```
rake shf:add_member_page[new_member_page]
 ....
[SHF_TASK] [shf:add_member_page] [info] Started at 2017-06-05 11:24:17 -0400
[SHF_TASK] [shf:add_member_page] [info] Created member page file: new_member_page.html
[SHF_TASK] [shf:add_member_page] [info] Finished at 2017-06-05 11:24:17 -0400.
[SHF_TASK] [shf:add_member_page] [info] Duration: 0.0 seconds.
[SHF_TASK] [shf:add_member_page] [info] Information was logged to: log/shf_tasks
```
### New Member Page list:
<img width="440" alt="screen shot 2017-06-05 at 11 26 25 am" src="https://cloud.githubusercontent.com/assets/9968213/26790477/d7667330-49e1-11e7-9259-2a90361594de.png">

### Edit title and contents of new page:
<img width="773" alt="screen shot 2017-06-05 at 11 27 01 am" src="https://cloud.githubusercontent.com/assets/9968213/26790512/f4e6ffb0-49e1-11e7-8df1-46870bcb7938.png">

Ready for review:
@weedySeaDragon @RobertCram @thesuss

2017-06-08 16:46 UTC, RobertCram reviewed
It is possible to use this rake task to put files anywhere in the directory structure. Should we perhaps add a sanitising check on the use of '/' in the filename?

2017-06-08 19:32 UTC, weedySeaDragon requested changes

2017-06-08 19:32 UTC, weedySeaDragon commented on lib/tasks/shf.rake
> +      filename = filename + '.html' unless filename =~ /.*\.html$/
agree with @RobertCram -- check for "risky" characters in the filename and just throw an error as discussed in our scrum.

2017-06-09 21:00 UTC, patmbolger commented
I added a check on filename characters - the only acceptable characters are limited to [a-zA-Z0-9_-.].

This is a reasonable set of characters file the member page filename.  The actual title of the page, of course, can be edited to something useful (title defaults to filename otherwise).

2017-06-09 21:20 UTC, weedySeaDragon commented on lib/tasks/shf.rake
> +      filename = filename + '.html' unless filename =~ /.*\.html$/
How about a slightly more informative error message:  `ERROR:  Unacceptable character(s) in the filename.  The acceptable characters are A-Z (upper- or lowercase), 0-9, '-' and '.'`

2017-06-09 21:23 UTC, weedySeaDragon requested changes

2017-06-09 21:23 UTC, weedySeaDragon commented on lib/tasks/shf.rake
> +      filename = filename + '.html' unless filename =~ /.*\.html$/
If you can make the error message more informative, then this looks good to me.

_(I should have made my previous comment above part of the review.)_

2017-06-09 21:30 UTC, patmbolger commented
I made the logged messages a little clearer for the case of invalid characters in filename.

(note that the `record` method (log instance method) writes to both a log file as well as STDOUT).

The user would see something like this:

```
Patricks-MBP:shf-project pbolger$ rake shf:add_member_page['file/;;;/name']

....

[SHF_TASK] [shf:add_member_page] [info] Started at 2017-06-09 17:26:45 -0400
[SHF_TASK] [shf:add_member_page] [error] Unacceptable characters in filename: file/;;;/name
[SHF_TASK] [shf:add_member_page] [error] Acceptable characters are a-z, A-Z, 0-9, '_', '-' and '.'
[SHF_TASK] [shf:add_member_page] [info] Finished at 2017-06-09 17:26:45 -0400.
[SHF_TASK] [shf:add_member_page] [info] Duration: 0.0 seconds.
[SHF_TASK] [shf:add_member_page] [info] Information was logged to: log/shf_tasks
```

2017-06-09 22:20 UTC, weedySeaDragon approved these changes

2017-06-11 10:08 UTC, RobertCram approved these changes

2017-06-11 16:35 UTC, merged