16 - Fixes some translations
AgileVentures/shf-project pull request #270
Opened 2017-06-09 10:51 UTC by thesuss

2017-06-09 13:39 UTC, patmbolger approved these changes

2017-06-09 17:37 UTC, weedySeaDragon requested changes

2017-06-09 17:37 UTC, weedySeaDragon commented on config/locales/sv.yml
> +      org_nr_no_hyphens: &orgnr_no_hyphens "Endast siffror (ej bindestreck)"
Good catch!  
So we also need to fix the `en.yml` file.

2017-06-15 18:54 UTC, weedySeaDragon approved these changes

2017-06-15 18:55 UTC, merged