Show all user emails - profile (login) as well as contact (application) emails
AgileVentures/shf-project pull request #293
Opened 2017-06-30 18:55 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/142975583

Changes proposed in this pull request:
1. User "show" view now shows profile (login) email 
2. User "show" view shows all applications for the user, including contact_email for each
3. Membership Application "show" view shows both user emails - profile and contact

Screenshots (Optional):
### User with two applications:
---

<img width="774" alt="screen shot 2017-06-30 at 2 53 08 pm" src="https://user-images.githubusercontent.com/9968213/27749973-ded849d8-5da3-11e7-9a84-61ff23b06ba0.png">

---
### Membership Application page:

<img width="554" alt="screen shot 2017-06-30 at 2 53 58 pm" src="https://user-images.githubusercontent.com/9968213/27750009-fbbfffc8-5da3-11e7-9bb5-05b214e083b2.png">

Ready for review:
@weedySeaDragon @RobertCram @thesuss

2017-07-04 18:47 UTC, weedySeaDragon requested changes
2 minor changes, but otherwise looks good!

2017-07-04 18:47 UTC, weedySeaDragon commented on app/views/users/show.html.haml
> +    %strong #{t('applications')}:
assign a style  & set the style to use 'strong' instead of coding `strong` in here directly.

2017-07-04 18:47 UTC, weedySeaDragon commented on app/views/users/show.html.haml
> +  %strong #{t('user_activity')}:
use a style instead of hardcoding `strong` here

2017-07-04 21:58 UTC, patmbolger commented on app/views/users/show.html.haml
> +    %strong #{t('applications')}:
That is not CSS but an HTML tag.  https://www.w3schools.com/tags/tag_strong.asp

2017-07-06 16:58 UTC, weedySeaDragon approved these changes

2017-07-10 14:55 UTC, RobertCram approved these changes

2017-07-13 19:58 UTC, merged