User Profile Management
AgileVentures/shf-project pull request #303
Opened 2017-07-16 14:56 UTC by RobertCram

PT Story: https://www.pivotaltracker.com/story/show/147882825

**Changes proposed in this pull request:**

1. Add first and last name fields to the Devise new registration and edit registration views.
2. Make first and last name required fields on user creation (before they were only required when editing a user)

**Note:**

This story does NOT include a UI link to the edit registration view. For that, see story  https://www.pivotaltracker.com/story/show/148847945

Ready for review:
@patmbolger @weedySeaDragon @thesuss

2017-07-16 22:14 UTC, patmbolger requested changes
Please see comments.

2017-07-16 22:14 UTC, patmbolger commented on app/views/devise/registrations/edit.html.haml
>      = devise_error_messages!
We need to customize error treatment to be consistent with our other views.  (see similar changes in PR: https://github.com/AgileVentures/shf-project/pull/297/files)

In particular, this line should be replaced by:
```
if resource.errors.any?
  .wpcf7-response-output
    - resource.errors.full_messages.each do |msg|
      = msg
```

2017-07-16 22:14 UTC, patmbolger commented on app/views/devise/registrations/new.html.haml
>      = devise_error_messages!
Same comment as above.

2017-07-17 10:15 UTC, RobertCram commented on app/views/devise/registrations/edit.html.haml
>      = devise_error_messages!
I've made the requested change, with one minor difference: I had to add a break after the individual messages. The code above as is would put multiple error messages on one line.

2017-07-17 10:20 UTC, patmbolger commented on app/views/devise/registrations/edit.html.haml
>      = devise_error_messages!
Yup, thats how all of our validation errors appear now.  I have a story open to replace the error-handling code with a helper method that returns styled HTML for error display - we can fix this issue there.

2017-07-17 10:28 UTC, RobertCram commented on app/views/devise/registrations/edit.html.haml
>      = devise_error_messages!
That's not what I am seeing. The errors on the membership application page seem to render correctly without the added breaks.

2017-07-17 11:23 UTC, patmbolger commented on app/views/devise/registrations/edit.html.haml
>      = devise_error_messages!
Yes, for MA `create` we use this logic:
```
- if @membership_application.errors.any?
  - @membership_application.errors.full_messages.each do |msg|
    .wpcf7-response-output
      = msg
```
whereas in other places we use this kind of logic:
```
.wpcf7-response-output
  - @member_app_waiting_reason.errors.full_messages.each do |msg|
    = msg
```
The styling for `wpcf7-response-output` class includes `text-align:center;`.  If each message is separately styled (first example above) this forces each message to occur on a separate line.  The second example shows all messages on a single (centered) line.

We're all over the map here and thus we need to standardize this.

Also, here is another issue I just noticed: https://www.pivotaltracker.com/story/show/148990401

2017-07-18 11:17 UTC, patmbolger approved these changes

2017-07-20 18:12 UTC, weedySeaDragon approved these changes

2017-07-21 08:35 UTC, merged