Selenium chrome spike sprint20
AgileVentures/shf-project pull request #319
Opened 2017-07-31 17:45 UTC by Zsuark

PT Story: https://www.pivotaltracker.com/story/show/148950573

Changes proposed in this pull request:
1. Adds in `@selenium` (headless) and `@selenium_browser` (displayed) chrome browser
2. Adds in `/^I confirm the popup$/` to the step definitions. NOTE: `/^I confirm popup$/` remains for poltergeist use

Ready for review

2017-07-31 19:54 UTC, RobertCram approved these changes
It seems the Semaphore error is just a fluke (I tried a copy of the same PR and it passed). If you remove the #TODO comment in the gem file and commit again, I'm fairly sure the build will pass.

Headless chrome not recognising alerts seems to be a well known problem. There is a bug report here:

https://bugs.chromium.org/p/chromium/issues/detail?id=696439

And someone trying to workaround it in Capybara here:

https://github.com/teamcapybara/capybara/commit/12c10059709346bfeadb2cea18f510174d842303

2017-08-07 12:33 UTC, patmbolger requested changes
Please see comments.

2017-08-07 12:33 UTC, patmbolger commented on features/step_definitions/basic_steps.rb
> +
Recommend consolidating this and the prior method to this:

```
When /^I confirm popup$/ do

  if Capybara.current_driver == :poltergeist
    using_wait_time 3 do
      page.driver.accept_modal(:confirm)
    end
  elsif Capybara.current_driver == :selenium_browser
    page.driver.browser.switch_to.alert.accept
  else
    raise 'step not configured for current browser driver'
  end

end
```

2017-08-07 12:33 UTC, patmbolger commented on features/support/env.rb
> +# TODO: Needed?
No, we don't need line 69.  Our `hooks.rb` handles this.

2017-10-03 12:29 UTC, patmbolger commented
Closing this PR and creating a new PR to replace.

2017-10-03 12:29 UTC, closed without merging