Allow variable number of users in seeding.
AgileVentures/shf-project pull request #325
Opened 2017-08-03 16:15 UTC by RobertCram

PT Story: https://www.pivotaltracker.com/story/show/148949923

**Changes proposed in this pull request:**

1. Allow for a variable number of users in development seeding. When needed (e.g. when working on the seeding logic), add the line `SEED_USERS=<number of users>` to the `.env` file to speed up seeding. If the `SEED_USERS` environment variable is not present, the number of users to seed reverts to the usual 100.

2. Rename `seed_spec.rb` to `seed_production_spec.rb` and add tests for development seeding in `seed_development_spec.rb`

Ready for review:
@patmbolger @weedySeaDragon

2017-08-07 13:16 UTC, patmbolger approved these changes
Looks good and restructure helps a lot.

One minor spelling issue.

2017-08-07 13:16 UTC, patmbolger commented on spec/db/seed_development_spec.rb
> +  it "adresses are in the db" do
`addresses ....`

2017-08-14 06:21 UTC, weedySeaDragon requested changes

2017-08-14 06:21 UTC, weedySeaDragon commented on db/seeds.rb
> +  number_of_users = (ENV['SEED_USERS'] || SEED_USERS).to_i
I'd like to prefix the variables we use with "SHF_", so I'd like this one to be `SHF_SEED_USERS`

And this needs to be added to `.env.example`  perhaps with something like this in the

 `# These are optional environment variables:` section:`

```
# SHF_SEED_USERS=25     # The number of users to create during seeding.  (Takes precedence of the default number in seeds.db)

```

2017-08-16 13:53 UTC, RobertCram commented on db/seeds.rb
> +  number_of_users = (ENV['SEED_USERS'] || SEED_USERS).to_i
Done,  @weedySeaDragon .

2017-08-17 16:37 UTC, weedySeaDragon approved these changes

2017-08-17 16:37 UTC, merged