Address is shown/instantiated for a newly approved member (company edit page)
AgileVentures/shf-project pull request #327
Opened 2017-08-06 22:24 UTC by weedySeaDragon

PT Story:  New Member: editing their company -address fields not shown
https://www.pivotaltracker.com/story/show/148622121

When a newly approved member went to edit his/her company page, the address fields were not being shown because no address was instantiated. 

## Changes proposed in this pull request:
1.  Created a feature that goes through the entire process of a user applying for membership, an admin approving it, and the user (now a member) logging in and editing their company information.   (We didn't have a feature that went through the entire process, so this error was not being caught. )
1.  `kommun` is optional for an Address (since when the admin approves the application and the company is created, we need to have a `main_address,` but the kommun might not be known at that point.  [Otherwise we'll need to have a default kommun to assign to new, empty addresses.]
2.  Company.`main_address` will instantiate an Address when called
3.  Pull 'address' part of the company form view into a partial (first step toward being able to show multiple addresses

Ready for review:
@thesuss @RobertCram @patmbolger

2017-08-08 10:31 UTC, patmbolger approved these changes
Looks good.

2017-08-16 15:43 UTC, RobertCram requested changes

2017-08-16 15:43 UTC, RobertCram commented on app/controllers/companies_controller.rb
>    end
Being lazy initialisation, I don't think we need this line here.

2017-08-16 15:43 UTC, RobertCram commented on features/user-applies-approved-edits-co.feature
> +
I think we should also add a feature for the sad path (where company name and the address fields are not filled in by the member). At the moment they are shown as required fields, but there are no error messages when left blank.

2017-08-16 16:36 UTC, RobertCram commented on features/user-applies-approved-edits-co.feature
> +
Sorry, I see that's supposed to be another story (https://www.pivotaltracker.com/story/show/141168775)

2017-08-16 16:38 UTC, RobertCram approved these changes

2017-08-18 23:28 UTC, merged