Do not allow delete of a company "mail" address
AgileVentures/shf-project pull request #375
Opened 2017-10-09 18:07 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/151803266

Changes proposed in this pull request:

In address `edit` view (for `mail` address):

1. Tell user that this is the company's `mail` address (and can't be deleted)
2. Do not show `Delete this address` button

Screenshot: `edit` view for company address:

<img width="624" alt="screen shot 2017-10-09 at 2 02 43 pm" src="https://user-images.githubusercontent.com/9968213/31351965-0c900680-acfb-11e7-90a7-38f9f4b29974.png">

Ready for review:
@weedySeaDragon @RobertCram @thesuss

2017-10-09 22:13 UTC, weedySeaDragon requested changes
Need to provide information to the user on what they need to do if they really want to delete this address.  From the PT user story (emphasis mine):

> 2. Provide a message to the user that they cannot delete a `mail` address, and **should specify another address as `mail` if they want to delete this address.  (perhaps static text somewhere, or a tooltip, ...).**

2017-10-10 17:55 UTC, weedySeaDragon approved these changes

2017-10-10 17:56 UTC, weedySeaDragon commented
Code all looks good.  Good to see the tooltip.   I think now we should get feedback from the client(s) and users and adjust as needed.

2017-10-12 16:59 UTC, thesuss approved these changes

2017-10-12 17:54 UTC, merged