email new applicant acknowledging their application was recevied
AgileVentures/shf-project pull request #380
Opened 2017-10-12 23:34 UTC by weedySeaDragon

### PT Story:  Send applicant email acknowledging that their application was received
https://www.pivotaltracker.com/story/show/151614904

## Changes proposed in this pull request:
1.  Send email when a new membership application is successfully submittted (saved)
2. In the flash message that appears, tell them that email is on the way.

Ready for review:
@AgileVentures/shf-project-team

2017-10-13 17:39 UTC, thesuss requested changes

2017-10-13 17:39 UTC, thesuss commented on config/locales/sv.yml
> +      success: "Tack, din ansökan har skickats. Du borde få ett mail inom kort på %{email_address} med information om vad du kan förvänta sig nästa."
success: "Tack, din ansökan har skickats. Du borde få en bekräftelse inom kort till %{email_address}."

2017-10-14 16:22 UTC, thesuss approved these changes

2017-10-16 14:22 UTC, patmbolger commented on features/emails/new-applicantion-gets-ack-email.feature
> +  I should get an email acknowleding my new application
^^ mispelling

2017-10-16 14:22 UTC, patmbolger commented on features/emails/new-applicantion-gets-ack-email.feature
> +  I should get an email acknowleding my new application
Also, please fix the misspelling in the file name.

2017-10-16 14:22 UTC, patmbolger commented on features/emails/new-applicantion-gets-ack-email.feature
> +  I should get an email acknowleding my new application
Actually, this file looks like it was replaced by the one below, so it should be removed(?)

2017-10-16 14:22 UTC, patmbolger commented on features/emails/new-application-gets-ack-email.feature
> +  I should get an email acknowleding my new application
mispelling

2017-10-17 10:15 UTC, patmbolger approved these changes

2017-10-19 14:20 UTC, RobertCram approved these changes

2017-10-19 14:21 UTC, RobertCram approved these changes
Thanks for leaving this open. I learned a lot "reviewing" it.

2017-10-19 18:54 UTC, merged