Add pagination to users index view.
AgileVentures/shf-project pull request #405
Opened 2017-11-20 15:33 UTC by RobertCram

PT Story: https://www.pivotaltracker.com/story/show/150853535

**Changes proposed in this pull request:**

1. Rewrite users controller `index` method to add pagination to the users index view.

2. Rewrite users `_search_form.html.haml` view to make ransack use the membership filter settings

3. Remove unnecessary scopes `are_members` and `are_not_members` on user.

Ready for review:
@patmbolger @weedySeaDragon @thesuss

2017-11-20 15:37 UTC, RobertCram commented on app/views/users/_users_list.html.haml
> +#users_list
I changed this to be in line with earlier implementations (companies_list, membership_applications_list).

2017-11-20 16:33 UTC, weedySeaDragon approved these changes

2017-11-21 12:12 UTC, patmbolger requested changes

2017-11-21 12:12 UTC, patmbolger commented on app/controllers/users_controller.rb
> +    action_params, @items_count, items_per_page = process_pagination_params('company')
The argument to `process_pagination_params` has to be unique across all uses of that method.  Here, `user` would suffice.

(we need a story to set up a registry of entities (argument) to be used for this method to ensure uniqueness for each use.  The entity designation is used to set `session` variables so we can remember the user's `items-per-page` and search criteria (the latter needs to be recalled when changing the items-per-page).

2017-11-21 12:12 UTC, patmbolger commented on app/controllers/users_controller.rb
>      render partial: 'users_list', locals: { q: @q, users: @users } if request.xhr?
Might as well as `items_count` to the `locals` hash while we're at it.

2017-11-21 12:12 UTC, patmbolger commented on app/views/users/_users_list.html.haml
> +                     items_count: @items_count,
Use local value `items_count` here (if you are passing this in as a local var from the controller).

2017-11-21 12:16 UTC, patmbolger commented
@RobertCram - please see code comments.

In addition, column sorting (member number, email) does not work.  This is because the original implementation of users search left off the required class in the sort link in the view.

For example, in `_users_list.html.haml` changing this statement:
```
%th= sort_link(q, :padded_membership_number, t('users.users_list.membership_number'), {}, 
{ remote: true } )
```
to this:
```
%th= sort_link(q, :padded_membership_number, t('users.users_list.membership_number'), {},
          { class: 'users_pagination', remote: true } )
```
enables sorting on this column.

2017-11-21 12:19 UTC, RobertCram commented on app/controllers/users_controller.rb
> +    action_params, @items_count, items_per_page = process_pagination_params('company')
A, yes, that's a copy & paste error. We do have a story somewhere to bring all the index views in line (code as well as appearance). When working on this story I realised I would like to have a helper to do most of the index view and pagination stuff for the different models. At the moment it feels like a lot of repetitive work. 

Do you think that might be an idea?

2017-11-21 12:22 UTC, patmbolger commented on app/controllers/users_controller.rb
> +    action_params, @items_count, items_per_page = process_pagination_params('company')
Yes, absolutely.  We've now done it enough times for a clear pattern to emerge - which we can refactor for reuse (and avoid repetition).

2017-11-21 12:24 UTC, patmbolger commented on app/controllers/users_controller.rb
> +    action_params, @items_count, items_per_page = process_pagination_params('company')
We do have the params processing method, and the pagination footer, which encapsulate much of the heavy lifting, but I am sure there is more opportunity to generalize further.

2017-11-29 12:55 UTC, patmbolger commented on app/controllers/users_controller.rb
> +    action_params, @items_count, items_per_page = process_pagination_params('company')
@RobertCram - I think you're still missing this one change (copy-and-paste error fix).  When that's done we can merge this PR.

2017-11-30 19:46 UTC, patmbolger approved these changes

2017-11-30 19:46 UTC, merged