Email admin(s) when a new application is submitted
AgileVentures/shf-project pull request #415
Opened 2017-12-01 18:15 UTC by weedySeaDragon

**PT Story: https://www.pivotaltracker.com/story/show/149374145**

### Changes proposed in this pull request:
1.  send all admins an email when a new membership application is submitted 
2.  added  `admins` scope for User so that we can get all admins and send email to them
3.  added details to the email so that the admin can see the number of files uploaded for the application.  (Recently a user said she uploaded files but they weren't in SHF.  Providing this info in the email to the admins will help admins to know if the files were successfully uploaded and saved in SHF or not.)

### Screenshots (Optional):

**text version:**

<img width="593" alt="shf-admin-new-app-text" src="https://user-images.githubusercontent.com/673794/33496772-6252adc6-d680-11e7-9f86-e92437e57a45.png">

** html version:**

<img width="524" alt="shf-admin-new-app-html" src="https://user-images.githubusercontent.com/673794/33496782-684c6e56-d680-11e7-8c8e-9660480fa3a1.png">

### Ready for review:
@AgileVentures/shf-project-team

2017-12-02 09:51 UTC, thesuss approved these changes

2017-12-02 14:15 UTC, patmbolger requested changes
Looks good.  Tested and worked for me.

See one suggested change.

2017-12-02 14:15 UTC, patmbolger commented on app/mailers/admin_mailer.rb
> +    @recipient_email = set_recipient_email admin
Don't need these assignments as the utility methods already set the instance var, i.e. these statements should be:
```
set_greeting_name admin
set_recipient_email admin
```

2017-12-02 22:24 UTC, weedySeaDragon commented on app/mailers/admin_mailer.rb
> +    @recipient_email = set_recipient_email admin
good catch!

2017-12-02 22:34 UTC, weedySeaDragon commented
@thesuss Should we add some wording in this email to point out that payment is still needed?
(I thought of this after your comment in #416 ).

2017-12-03 11:03 UTC, patmbolger approved these changes

2017-12-03 12:00 UTC, RobertCram requested changes

2017-12-03 12:00 UTC, RobertCram commented on app/controllers/membership_applications_controller.rb
> +        MembershipApplicationMailer.acknowledge_received(@membership_application).deliver
It seems `deliver` is deprecated (?), so you might want to change this to `deliver_now`

2017-12-03 12:00 UTC, RobertCram commented on app/controllers/membership_applications_controller.rb
>        if new_file_uploaded(params)
There is a problem here that is not directly related to this PR, but should be addressed: If one of the files is too big or has an unacceptable extension, the application will be saved but the email message will never be send (`new_file_uploaded` fails). If the files are added in a second attempt, the action has now become an edit operation, and again no message will be send.

2017-12-03 12:09 UTC, thesuss commented
@weedySeaDragon The wording is perfect. But not for this event. Its perfect for when the membership fee has been paid. It needs to be completely exchanged. Will have to look into it deeper. Can do tomorrow before the meeting I hope.

2017-12-03 22:04 UTC, weedySeaDragon commented
@thesuss :  I added the names of the files uploaded.  Is this OK?

2017-12-04 08:07 UTC, thesuss commented
@weedySeaDragon 
File-names are usually irrelevant. Most come from FB and have names like "24312415_905701216265640_3935260062927433455_n" I think that might trigger spam flags in the e-mail?

2017-12-05 13:20 UTC, RobertCram approved these changes

2017-12-07 14:26 UTC, merged