Remove beta test code and related items
AgileVentures/shf-project pull request #423
Opened 2017-12-08 11:59 UTC by patmbolger

PT Story: #153473901

To remove beta test scaffolding:
1. Deploy this PR 
2. Remove this line from `.env`: ```SHF_BETA=yes```
3. Remove file `config/initializers/beta_test.rb`

Ready for review:
@AgileVentures/shf-project-team

2017-12-11 17:17 UTC, RobertCram approved these changes

2017-12-11 18:48 UTC, aleciavogel requested changes

2017-12-11 18:48 UTC, aleciavogel commented on app/views/companies/show.html.haml
> +        - if current_user.is_in_company_numbered?(@company.company_number) || |
I would create a helper method for this

2017-12-14 18:04 UTC, patmbolger commented on app/views/companies/show.html.haml
> +        - if current_user.is_in_company_numbered?(@company.company_number) || |
@aleciavogel - thanks, thats a good idea.  Since it's a bit beyond the intent of this PR, I created a new chore for that.

https://www.pivotaltracker.com/story/show/153591697

2017-12-14 18:59 UTC, merged