Proof of membership
AgileVentures/shf-project pull request #468
Opened 2018-02-03 12:03 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/152839567

Changes proposed in this pull request:
1. Using IMGKit to convert HTML to image (jpeg)
2. Assemble proof-of-membership (POM) image using components including "app config" items (chairperson signature, SHF logo), member photo, and membership information. 
3. Allow member to download JPG image of POM, for use elsewhere
4. Also provide a HTML view of the POM by itself, in case member wants to take their own screenshot and use that instead (or in addition to) the JPG image, or, the member wants to use this link on their own website (instead of using the image directly - this will result in an always-updated POM to be created on demand).
5. Removed ENV guard that prevented the member from seeing the member photo upload form (in their profile-edit page).  Now the member sees that.

The member accesses their POM in the login-menu item "View Your Account".

Prerequisites to deployment:

1. Deploy to heroku and confirm it works there
2. Deploy to DO (staging) and confirm
3. In production, in "app configuration", add/update the chairperson signature and the SHF logo (this step can be done as part of the production deployment - images for this are included in this PR).

Follow-on story to be created in PT:

  The JPG image has an 8 px margin, imposed by the user agent (browser).  This should be removed in the image, either through CSS or perhaps some image manipulation tool.

Screenshots (Optional):
### Member account view (zoomed out to see entire page):

<img width="726" alt="screen shot 2018-02-03 at 7 01 21 am" src="https://user-images.githubusercontent.com/9968213/35766942-150fb2d6-08b0-11e8-99e4-9af9d1eb02b4.png">

### Result of clicking "Show Image" in prior page (actual size):

<img width="360" alt="screen shot 2018-02-03 at 7 01 59 am" src="https://user-images.githubusercontent.com/9968213/35766946-2b4c7db8-08b0-11e8-830a-19bcd23c9c6b.png">

### Image produced by "Download Image" button:

<img width="572" alt="screen shot 2018-02-03 at 7 02 37 am" src="https://user-images.githubusercontent.com/9968213/35766951-418e0132-08b0-11e8-922d-3fed5fea725e.png">

Ready for review:
@AgileVentures/shf-project-team

2018-02-05 14:57 UTC, patmbolger commented
**Update Feb 5**:  Allow member-info area to expand as needed to accommodate any number of categories:

<img width="293" alt="screen shot 2018-02-05 at 9 24 40 am" src="https://user-images.githubusercontent.com/9968213/35810855-080aad5a-0a5b-11e8-9118-28232d37c3d7.png">

2018-02-07 11:19 UTC, thesuss requested changes

2018-02-07 11:19 UTC, thesuss commented on config/locales/sv.yml
> +      proof_of_membership: Bevis på medlemskap
Behörighetsbevis

2018-02-07 11:19 UTC, thesuss commented on config/locales/sv.yml
> +      proof_of_membership_describe: Den här bilden är ditt bevis på medlemskap i SHF.
/* Remember we are moving away from the use of "SHF" */ 

Detta är ditt behörighetsbevis.

2018-02-07 11:19 UTC, thesuss commented on config/locales/sv.yml
> +                                 tryckt ut och visas på din verksamhetsort.
tryckt ut och visas på din verksamhetsort. = 
skriva ut den och visa upp fysiskt i möten med kunder.

2018-02-07 11:19 UTC, thesuss commented on config/locales/sv.yml
> +      proof_of_membership_show: Eller du kan ta en skärmdump av bilden och använda
Eller du kan ta = 
Du kan även ta

2018-02-07 11:19 UTC, thesuss commented on config/locales/sv.yml
> +                                gå till en sida med bara den presenterade bilden.
med bara den presenterade bilden. = 
som bara innehåller bilden.

2018-02-07 11:19 UTC, thesuss commented on app/assets/stylesheets/proof-of-membership.css
> +.parent-div {
@import url('https://fonts.googleapis.com/css?family=Open+Sans');
body {
    font-family: 'Open Sans', sans-serif;
}

2018-02-07 11:19 UTC, thesuss commented on app/assets/stylesheets/proof-of-membership.css
> +.parent-div {
(above .parent-div, clearly)

2018-02-08 14:23 UTC, thesuss approved these changes

2018-02-12 22:03 UTC, patmbolger commented
**Update Feb 12**

The number of files changed greatly increased due to concurrent updates to specific gems in use, including
  - cucumber (2.4 > 3.1)
  - font-awesome (4.7 > 5.0)
  - spec (3.6 > 3.7)

and others.

This caused many unrelated things to break.

2018-02-13 15:55 UTC, merged