User delete feature (for admin)
AgileVentures/shf-project pull request #555
Opened 2018-10-29 14:32 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/161365399

NOTEL this PR is built on top of the rails-upgrade PR (https://github.com/AgileVentures/shf-project/pull/554).

The actual number changed files for _this_ PR are:

```
modified:   app/controllers/users_controller.rb
modified:   app/views/users/_user.html.haml
modified:   app/views/users/_users_list.html.haml
modified:   config/locales/en.yml
modified:   config/locales/sv.yml
modified:   features/manage_users.feature
```

Changes proposed in this pull request:
1. Add delete icon (garbage can) to users index view
2. Controller action
3. Cucumber test

Screenshots (Optional):
<img width="779" alt="screen shot 2018-10-29 at 10 28 53 am" src="https://user-images.githubusercontent.com/9968213/47656649-d82fef00-db65-11e8-9e81-0f7eb4122f35.png">

---

<img width="768" alt="screen shot 2018-10-29 at 10 30 22 am" src="https://user-images.githubusercontent.com/9968213/47656663-dc5c0c80-db65-11e8-99c2-ee606902a5f0.png">

Ready for review:
@

2018-11-01 19:53 UTC, weedySeaDragon requested changes
Looks good with that 1 minor i18n change.

2018-11-01 19:53 UTC, weedySeaDragon commented on app/views/users/_user.html.haml
> +              :data => {:confirm => "Delete #{user.full_name}?"}
need translation for confirmation message:  `:confirm => "#{t(delete...)} #{user.full_name}?"`

2018-11-02 18:25 UTC, patmbolger commented on app/views/users/_user.html.haml
> +              :data => {:confirm => "Delete #{user.full_name}?"}
@weedySeaDragon - wow, I can't believe I forgot about translation!  Thanks for catching that - fixed now.

2018-11-02 21:22 UTC, weedySeaDragon commented on app/views/users/_user.html.haml
> +              :data => {:confirm => "Delete #{user.full_name}?"}
@patmbolger I bet you left that out just to give me something to do. ;-)

2018-11-02 21:22 UTC, weedySeaDragon approved these changes

2018-11-02 21:22 UTC, merged