Create Dinkurs Fetch a condition class
AgileVentures/shf-project pull request #593
Opened 2018-12-28 21:04 UTC by patmbolger

PT Story: https://www.pivotaltracker.com/story/show/162494826

Changes proposed in this pull request:
1. condition class
2. condition record (added to load_conditions.rake)
3. tests

Ready for review:
@AgileVentures/shf-project-team

2018-12-28 21:29 UTC, weedySeaDragon requested changes
I don't think we need to write a `.feature` for this (I think everything is tested in the spec) but want to just mention the thought in case it makes you think of scenarios that would be illuminating / tricky by setting up data in a feature.

Other than that,  mostly refactoring comments. :-)

2018-12-28 21:29 UTC, weedySeaDragon commented on app/models/conditions_response/dinkurs_fetch.rb
> +    unless timing_is_every_day?(get_timing(condition))
Since we need to do this with every ConditionResponder, can this be generalized?  Then this & other ConditionResponder subclasses can call or use the generalized method(s).

Not required for this PR, but would be helpful.

2018-12-28 21:29 UTC, weedySeaDragon commented on app/models/conditions_response/dinkurs_fetch.rb
> +    Company.where.not(dinkurs_company_id: [nil, '']).order(:id).each do |company|
This should be a method (or scope) in the Company class.  Then this class can just call it (and the specific implementation details of it remains in the Company class).  (And then we'll need the spec/test for it in company_spec.rb of course)

2018-12-28 21:29 UTC, weedySeaDragon commented on spec/models/conditions_response/dinkurs_fetch_spec.rb
> +      it 'Fetches events for companies with dinkurs_id' do
This is really just checking the log file, so the description needs to change.
(It's correct to just check the log file here.  Let the `company_spec.rb` verify that it is/is not actually fetching the right stuff.)

Ditto with `it 'Does not attempt to fetch events for company without dinkurs_id'` below.

2018-12-29 12:22 UTC, patmbolger commented on app/models/conditions_response/dinkurs_fetch.rb
> +    unless timing_is_every_day?(get_timing(condition))
good idea - added that.

2018-12-29 12:40 UTC, patmbolger commented on spec/models/conditions_response/dinkurs_fetch_spec.rb
> +      it 'Fetches events for companies with dinkurs_id' do
I agree that confirming that the dunkers fetch occurs, and that the right events are returned, processed and stored in the DB, is the responsibility of various unit tests.

However, what I want to test here is to confirm that the response is actually _invoking_ the fetch functionality, which is its responsibility.  So, to do that I am checking for a side-effect of that activity.

Of course, I could have used `expect_any_instance_of` (Company) to check that, but the Rspec authors recommend not using that, except for specific situations (e.g. testing legacy code).

Neither approach is very satisfying, nor is not having a test for this.

2018-12-29 14:04 UTC, patmbolger commented on app/models/conditions_response/dinkurs_fetch.rb
> +    Company.where.not(dinkurs_company_id: [nil, '']).order(:id).each do |company|
yes, done.

2018-12-30 00:08 UTC, weedySeaDragon commented on spec/models/conditions_response/dinkurs_fetch_spec.rb
> +      it 'Fetches events for companies with dinkurs_id' do
The way you're doing that makes total sense.  (And I agree that `expect_any_instance_of` would not be good.)  I think that the descriptions used ".... log file" +  before you made the recent changes to have company_spec test for the specific fetching, it was leaning 'wrong' to me.

My tendency would be to change the descriptions to be more of what you just said: _"what I want to test here is to confirm that **the response is actually invoking the fetch functionality**,"_
but it's not a big deal now.  (pulling the responsibility out to the Company class was much more important.)

2018-12-30 00:10 UTC, weedySeaDragon commented
Interesting that this is failing a cucumber test -- as are other recent PRs.  <sigh>

2018-12-30 00:10 UTC, weedySeaDragon approved these changes

2018-12-31 20:06 UTC, merged