Sprint58:  mail contents for the H-Branding fee past due alert email
AgileVentures/shf-project pull request #595
Opened 2018-12-30 04:59 UTC by weedySeaDragon

### PT Story:  Email alert: to all in a company: H-branding is not paid
https://www.pivotaltracker.com/story/show/161889566

This PR is open so that the email _contents_ can be specified.
@thesuss -- This PT story is all ready except for the contents of the emails.  You can update this PR yourself or let me know what the text should be.

### Changes proposed in this pull request:
1. 

Ready for review:
@thesuss

2019-01-01 17:28 UTC, thesuss commented
I dont see the suggested text? 

Here's a suggestion where I just changes 4 words. 

Hej FULLNAME

Observera att **ditt företags** nuvarande **H-märkespremie** löper ut DATE.

Du kan förlänga **den** i ytterligare 12 månader genom att betala.

Mitt **företag** (du kan behöva logga in först innan länken fungerar).

2019-01-01 20:40 UTC, weedySeaDragon commented
@thesuss  the view file for that mail is what needs to be completed.

 https://github.com/AgileVentures/shf-project/blob/01d35c65dbd6818fd33d3060f0d15f1f2a1aa0fe/app/views/member_mailer/h_branding_fee_past_due.html.haml

I think what I sketched out is pretty close to what you have.  (But if not, fix it).
As usual, you need to make sure the local file entries are correct.

2019-01-01 22:24 UTC, thesuss requested changes

2019-01-01 22:24 UTC, thesuss commented on config/locales/en.yml
> +          account_login_html: "%{account_link} (you may need to login first before the link works)."
It needs to be company page login

           fee_is_unpaid: Please note that your current H-branding fee is unpaid.
          how_to_pay_fee: You can pay your H-branding for another
                             12 months by paying the fee. This makes you visible on the map. 
          company_login_html: "%{company_link} (you may need to login first before you can see the button to pay)."

2019-01-01 22:24 UTC, thesuss commented on config/locales/sv.yml
> +          account_login_html: "%{account_link} (you may need to login first before the link works)."
It needs to be company page login

`subject: Ditt företags H-märkespremie är obetald. `
 `fee_is_unpaid: Observera att ditt företags H-märkespremie inte är betald. `
`how_to_pay_fee: Betala den ett år till via länken nedan. Detta gör att du fortsätter synas på kartan och fortsätter ha ett H-märkt företag. `
`company_login_html: "%{company_link} (du kan behöva logga in först innan du ser knappen för att betala).`

2019-01-03 17:47 UTC, thesuss commented
I think its good, can you make a picture to make sure the link is in there? :)

2019-01-03 19:39 UTC, weedySeaDragon commented
@thesuss : I added the screenshots to the PR description.

(Thanks for reminding me to do that.)

2019-01-03 20:52 UTC, thesuss approved these changes

2019-01-03 21:30 UTC, merged