"design guide" page for admin
AgileVentures/shf-project pull request #652
Opened 2019-03-31 21:26 UTC by weedySeaDragon

### PT Story:  Design standards  (prelim. to Style guide)
https://www.pivotaltracker.com/story/show/164809369

### Changes proposed in this pull request:
1.  Created a "design guide page" (have to be logged in as admin) so we have a place to see, discuss, and maybe record design decisions.
    - after logging is as admin, go to <localhost shf url>/admin/designguide
    - it's rather hard coded.  Not sure that we ever should put this into production, but it gives
       us something to start with.  (This really helped me when working thru the NewLook PRs)
2. Converted _nearly_ all the stylesheets to `.scss` (SASS)  We should be using .scss so that
     we can DRY up the CSS and take advantage of the power of SASS.    _(Should be a PT story)_
    Needed to do this to be able to pull out all color hex codes into variables, which is what I used to get a list of all colors in use.  (Using variables for colors is one good example of using variables in CSS.  You can look at how Boostrap uses variables, for example.  That's what lets everyone just define their own color for $primary, etc., and have it be put into all of the bootstrap stuff.)
3. Found out the hard way that ImagesUtility _requires_ `.css` files, so the 2 files it requires are not converted to .scss

### Screenshots (Optional):

<img width="685" alt="designguide-toc" src="https://user-images.githubusercontent.com/673794/55295346-df7f5100-53c0-11e9-9dea-93daf1533d35.png">

<img width="616" alt="designguide-colors" src="https://user-images.githubusercontent.com/673794/55295345-dee6ba80-53c0-11e9-9dce-cdb1d731bb43.png">

<img width="603" alt="designguide-btbs" src="https://user-images.githubusercontent.com/673794/55295344-dee6ba80-53c0-11e9-8bda-c9439f6cf0df.png">

<img width="626" alt="designguide-btns-body" src="https://user-images.githubusercontent.com/673794/55295343-dee6ba80-53c0-11e9-9abb-f60a33e13cb2.png">

<img width="636" alt="designguide-alerts" src="https://user-images.githubusercontent.com/673794/55295342-dee6ba80-53c0-11e9-8c9c-71ec1d72c73c.png">
<img width="598" alt="designguide-text" src="https://user-images.githubusercontent.com/673794/55295341-dee6ba80-53c0-11e9-8fc9-7fddce70e4ce.png">

### Ready for review:
@thesuss @patmbolger @rmzse

2019-04-01 06:38 UTC, thesuss commented
![image](https://user-images.githubusercontent.com/7266909/55307973-7ef02280-5459-11e9-9a2a-483c2e17fafd.png)

2019-04-01 06:41 UTC, thesuss commented
![image](https://user-images.githubusercontent.com/7266909/55308099-ead28b00-5459-11e9-9a9a-8449fad94b45.png)

2019-04-01 06:42 UTC, thesuss commented
*wonders* is companies.scss even used anywhere anymore? 
I dont think so: 
```
@import "bootstrap";
@import "bootstrap-toggle";
@import "font-awesome-sprockets";
@import "font-awesome";
@import "maps";
@import "pagination";
@import "style";
@import "custom";
@import "dashboard";
```

2019-04-01 06:45 UTC, thesuss commented
May be Different PR, just want to have it noted
![image](https://user-images.githubusercontent.com/7266909/55308257-73e9c200-545a-11e9-9d7d-8f838903cb76.png)

2019-04-01 08:07 UTC, thesuss commented on app/views/admin_only/design_guide/show.html.haml
> +%div#design-guide{ class: "#{controller.action_name}" }
Agree

2019-04-01 08:09 UTC, thesuss commented
I was afraid to delete the page specific scss-files as I was unsure how/where they are called/used. But I dont think they are called/used.

2019-04-01 14:17 UTC, patmbolger commented
I really like this idea _and_ the scss cleanup.

NOTE: All bottom buttons should be centered (your example showing a right-aligned button is out of date, I believe).

2019-04-10 20:11 UTC, patmbolger commented
@weedySeaDragon Everything looks good except for the examples showing "button at the bottom of a page".

It looks like this:

---
<img width="770" alt="Screen Shot 2019-04-10 at 4 08 34 PM" src="https://user-images.githubusercontent.com/9968213/55909900-1583b880-5bab-11e9-8fc7-827778455ec0.png">

---

But the last 2 (of 3) of the examples are obsolete, since we standardized in _centering_ all buttons at the bottom of a page.  Examples:

---
<img width="773" alt="Screen Shot 2019-04-10 at 4 08 54 PM" src="https://user-images.githubusercontent.com/9968213/55909979-44019380-5bab-11e9-9b9b-549a527b0d95.png">

---

<img width="711" alt="Screen Shot 2019-04-10 at 4 09 04 PM" src="https://user-images.githubusercontent.com/9968213/55909990-46fc8400-5bab-11e9-9eaf-6a811a1a9b81.png">

2019-04-10 20:12 UTC, patmbolger requested changes
pls see comment

2019-04-14 10:28 UTC, patmbolger approved these changes

2019-04-14 21:10 UTC, merged