Payment Emails: Give them their login e-mail somewhere
AgileVentures/shf-project pull request #662
Opened 2019-04-12 03:39 UTC by weedySeaDragon

### PT Story: Use standard text to explain how to log in _and_ provide the user's login email as a reminder how to log in.
https://www.pivotaltracker.com/story/show/165126396

### Changes proposed in this pull request:
1.  Created a standard partials for common text:
    - logging in: the login page and user's login email
    - how to pay membership fee
    - how to pay H-markt fee
    - how to upload files
2. Revised emails to use the partials.  Emails had diverged, so I took this opportunity to revise them so they are standardized (using the partials).
3. removed no longer needed partials and locale entries
4. Locale entries

### Screenshots (Optional):

**Here is the current list of emails we send out via the alerts.** (This is the mailer preview page.) 
This PR only deals with those from the **Member mailer** and the **SHF Application Mailer.**
There are 10 emails to check, each in both Swedish (sv) and English (en).

<img width="451" alt="list-of-emails--previewer" src="https://user-images.githubusercontent.com/673794/56010402-4261c980-5c98-11e9-94a9-d2d67f46e979.png">

---

#### 1. Member mailer: app_no_uploaded_files

<img width="642" alt="email-app-no-uploaded-files--sv" src="https://user-images.githubusercontent.com/673794/56010389-41309c80-5c98-11e9-9bdd-de51475919e1.png">

---

<img width="654" alt="email-app-no-uploaded-files--en" src="https://user-images.githubusercontent.com/673794/56010388-41309c80-5c98-11e9-93bf-f58eac624246.png">

---
---

#### 2. Member mailer: company_info_incomplete

<img width="645" alt="email-co-info-incomplete--sv" src="https://user-images.githubusercontent.com/673794/56010391-41309c80-5c98-11e9-8176-f07d450a1f04.png">

---

<img width="627" alt="email-co-info-incomplete--en" src="https://user-images.githubusercontent.com/673794/56010390-41309c80-5c98-11e9-80a7-d2d7acb6b984.png">

---
---

#### 3. Member mailer: h_branding_fee_past_due

<img width="599" alt="email-hbranding-fee-past-due--en" src="https://user-images.githubusercontent.com/673794/56010392-41309c80-5c98-11e9-84bd-037a83254396.png">

---

<img width="634" alt="email-hbranding-fee-past-due--sv" src="https://user-images.githubusercontent.com/673794/56010393-41309c80-5c98-11e9-9ea5-864916ab1010.png">

---
---

#### 4. Member mailer: h_branding_fee_will_expire

<img width="643" alt="email-hbranding-will-expire--sv" src="https://user-images.githubusercontent.com/673794/56010395-41c93300-5c98-11e9-82cc-18c93dbb851b.png">

---

<img width="655" alt="email-hbranding-will-expire--en" src="https://user-images.githubusercontent.com/673794/56010394-41c93300-5c98-11e9-8d8f-0cd38cd699ad.png">

---
---

#### 5. Member mailer: membership_expiration_reminder

<img width="640" alt="email-membership-expiration-reminder--sv" src="https://user-images.githubusercontent.com/673794/56010397-41c93300-5c98-11e9-9c3a-3a371fbac265.png">

---

<img width="648" alt="email-membership-expiration-reminder--en" src="https://user-images.githubusercontent.com/673794/56010396-41c93300-5c98-11e9-8d80-d5a996ae4e97.png">

---
---

#### 6. Member mailer: membership_granted

<img width="641" alt="email-membership-granted--en" src="https://user-images.githubusercontent.com/673794/56010398-41c93300-5c98-11e9-9145-17b755b93ab7.png">

---

<img width="655" alt="email-membership-granted--sv" src="https://user-images.githubusercontent.com/673794/56010399-41c93300-5c98-11e9-99ed-02d612776f8e.png">

---
---

#### 7. Member mailer: membership_lapsed

<img width="647" alt="email-membership-lapsed--en" src="https://user-images.githubusercontent.com/673794/56010400-41c93300-5c98-11e9-96e8-984d0b726114.png">

---

<img width="642" alt="email-membership-lapsed--sv" src="https://user-images.githubusercontent.com/673794/56010401-4261c980-5c98-11e9-8262-385c10b20316.png">

---
---

#### 8. SHF Application mailer: acknowledge_received_no_files_uploaded

<img width="644" alt="email-ack-received-no-files-uploaded--en" src="https://user-images.githubusercontent.com/673794/56010383-40980600-5c98-11e9-83dd-14687a3b0852.png">

---

<img width="653" alt="email-ack-received-no-files-uploaded--sv" src="https://user-images.githubusercontent.com/673794/56010385-40980600-5c98-11e9-90b3-aaff29d6c4e6.png">

---
---

#### 9. SHF Application mailer: acknowledge_received_with_files_uploaded

<img width="632" alt="email-ack-received-files-uploaded--en" src="https://user-images.githubusercontent.com/673794/56010380-40980600-5c98-11e9-91bf-b540d813bbf6.png">

---

<img width="634" alt="email-ack-received-files-uploaded--sv" src="https://user-images.githubusercontent.com/673794/56010381-40980600-5c98-11e9-953c-a7192176a992.png">

---
---

#### 10. SHF Application mailer: app_approved

<img width="639" alt="email-app-approved--sv" src="https://user-images.githubusercontent.com/673794/56010387-41309c80-5c98-11e9-861f-4d8cff887442.png">

---

<img width="655" alt="email-app-approved--en" src="https://user-images.githubusercontent.com/673794/56010386-40980600-5c98-11e9-9791-f07cef94424e.png">

---
---

### Ready for review:
@thesuss

2019-04-15 16:19 UTC, thesuss commented on config/locales/sv.yml
> +    your_login_email_is: "Your login email is "
Din e-post för att logga in är:

2019-04-15 16:36 UTC, thesuss requested changes

2019-04-15 16:36 UTC, thesuss commented on config/locales/sv.yml
> +    how_to_pay_membership: "How to Pay Your Membership Fee:"
Så här betalar du medlemsavgiften:

2019-04-15 16:36 UTC, thesuss commented on config/locales/sv.yml
> +    pay_membership_step: "Once you are logged in, go to your account page to pay."
När du är inloggad hittar du betalknappen på ditt konto.

2019-04-15 16:36 UTC, thesuss commented on config/locales/sv.yml
> +    here_is_acct_page: "Here is your account page: "
Här är en länk till ditt konto:

2019-04-15 16:36 UTC, thesuss commented on config/locales/sv.yml
> +    how_to_pay_hmarkt: "How to Pay the H-Markt License Fee:"
Så här betalar du H-märkespremien:

2019-04-15 16:36 UTC, thesuss commented on config/locales/sv.yml
> +    h_brand_exp_shown: "THE H-MARKT LICENSE EXPIRATION WILL BE ON THE COMPANY PAGE."
**_I think this is said in "    pay_hmarkt_step:"_**

2019-04-25 13:21 UTC, thesuss commented
There are a bunch of language things, but I can do them separate

2019-04-25 13:21 UTC, thesuss approved these changes

2019-04-29 15:35 UTC, patmbolger approved these changes

2019-04-29 16:39 UTC, weedySeaDragon commented
Interesting that the cucumber tests failed on this one: 
```
  @selenium @time_adjust
  Scenario: Search by category and region                                                   # features/search_companies.feature:170
    Given I am Logged out                                                                   # features/step_definitions/user_steps.rb:27
    And I am on the "landing" page                                                          # features/step_definitions/navigation_steps.rb:1
    Then I select "Groomer" in select list t("activerecord.models.business_category.one")   # features/step_definitions/basic_steps.rb:76
    Then I select "Västerbotten" in select list t("activerecord.attributes.company.region") # features/step_definitions/basic_steps.rb:76
    And I click on t("search")                                                              # features/step_definitions/basic_steps.rb:7
    And I should not see "HappyMutts" in the list of companies                              # features/step_definitions/company_steps.rb:107
    And I should not see "We Luv Dogs" in the list of companies                             # features/step_definitions/company_steps.rb:107
    And I should not see "Barky Boys" in the list of companies                              # features/step_definitions/company_steps.rb:107
    And I should not see "Dogs R Us" in the list of companies                               # features/step_definitions/company_steps.rb:107
    Then I select "Stockholm" in select list t("activerecord.attributes.company.region")    # features/step_definitions/basic_steps.rb:76
    And I click on t("search")                                                              # features/step_definitions/basic_steps.rb:7
    And I should see "Barky Boys"                                                           # features/step_definitions/assertion_steps.rb:81
    Then I select "Sweden" in select list t("activerecord.attributes.company.region")       # features/step_definitions/basic_steps.rb:76
    And I click on t("search")                                                              # features/step_definitions/basic_steps.rb:7
    And I should see "We Luv Dogs"                                                          # features/step_definitions/assertion_steps.rb:81
      expected all ajax requests to be completed after scenario, but some ajax requests were still running. (RuntimeError)
      ./features/support/hooks.rb:29:in `After'
```

First time I've seen that scenario fail based on ajax.  The scenario that does the nearly same thing (in the same feature file) passed.

So am going to merge this.

2019-04-29 16:39 UTC, merged