Pages update
AgileVentures/shf-project pull request #67
Opened 2016-12-07 17:27 UTC by thesuss

Changed static pages after feedback from client

2016-12-07 18:28 UTC, mattnwa commented on app/helpers/application_helper.rb
> -  def user_has_membership_application?
Maybe Consul Gem would be smart for this type of Power check. Future roadmap?

2016-12-07 18:28 UTC, mattnwa approved these changes

2016-12-07 19:32 UTC, thesuss commented on app/helpers/application_helper.rb
> -  def user_has_membership_application?
We have Pundit (Policies) and are going to implement statesman, is this a third thing, or similar to one of them?

2016-12-07 23:45 UTC, weedySeaDragon requested changes
You can't delete 
    user_has_membership_application
because that method is needed to determine what menu items to show.

(that method is going to be refactored in the PR I'm working on.  so just leave it as is.)

After discussing it in Slack, I agree with you -- just delete it.  I will add it back in if I need it during the refactoring of the nav menus.  
**You Are Right About This.** :-)

2016-12-07 23:47 UTC, weedySeaDragon commented on app/helpers/application_helper.rb
> -  def user_has_membership_application?
There is overlap with Consul & Pundit.  Consul (as I understand it) provides additional functionality: it helps you control who can see what (like menu items).

I agree, @mattnwa , it would be good to consider it in the future.

2016-12-08 06:21 UTC, weedySeaDragon approved these changes

2016-12-08 06:22 UTC, merged