fixes the bug of company website url
AgileVentures/shf-project pull request #68
Opened 2016-12-07 18:14 UTC by thesuss

PT Story: https://www.pivotaltracker.com/story/show/135684103

Changes proposed in this pull request:
1. link_to @company.website, @company.website

2016-12-07 18:22 UTC, mattnwa approved these changes

2016-12-07 20:29 UTC, patmbolger commented
I recommend not merging this PR.  Please see my comment here: https://www.pivotaltracker.com/n/projects/1904891/stories/135684103

2016-12-07 23:52 UTC, weedySeaDragon requested changes
must update
  view_all_companies.feature

So that it's clear exactly what is expected
And so that we have a test for it

2016-12-08 07:04 UTC, weedySeaDragon approved these changes

2016-12-08 07:04 UTC, merged