[WIP] RFC on UX: Warn if user is paying before about [x] months when it is due
AgileVentures/shf-project pull request #710
Opened 2019-09-03 20:32 UTC by weedySeaDragon

## PT Story:  Warn if user is paying, but are already paid up > 2 months out
https://www.pivotaltracker.com/story/show/166273184

### This is a Request For Comments (RFC) on **_the UX only._** 
Once we have decided on the UX I will submit a new PR.  Comments and feedback on the implementation should be made on that PR.
-  I have not done any I18n work.  That will be done on the later PR.

## Changes proposed in this pull request:
1.  Implemented the number of days to use to determine when a user "should" pay in the Application Configuration. You can log in as an admin and see it (and change it) there.

2.  I changed the layout of the member's membership payment term and the company h-markt branding license term.  See the screenshots below for details.

3.  If they do not need to make a payment, a modal comes up when they click the payment button.  The modal explains that they don't need to make a payment, but they can.

Please give me feedback on the layout, design, and interaction.

## Screenshots:

I've done screenshots with and without annotations.   For some of these I've first shown the screenshot _without_ annotations so that it's easier to see the layout and design.  Below it is a screenshot with annotations.  It does make this long with all the images.

### _Member -  Membership: No payment is due now:_

<img width="690" alt="member-no-payment-needed" src="https://user-images.githubusercontent.com/673794/64204835-6e4e3900-ce4b-11e9-867d-02c063c7ead2.png">

<img width="690" alt="anntd-ae-member-no-payment-needed" src="https://user-images.githubusercontent.com/673794/64205269-6ba01380-ce4c-11e9-9d50-0b3355b78723.png">

---

_Tooltip for the payment button:_
---

<img width="682" alt="anntd-ae-member-no-payment-needed-tooltip" src="https://user-images.githubusercontent.com/673794/64205268-6ba01380-ce4c-11e9-908e-14bdc55a0601.png">

---

_Modal that comes up when payment button is clicked: (In the 2nd screenshot, the underlined in red shows the words that are different from the Company branding license modal below.)_
---

<img width="681" alt="modal-no-pay-needed-member" src="https://user-images.githubusercontent.com/673794/64204838-6ee6cf80-ce4b-11e9-96f0-a925f9c6a3cb.png">

<img width="681" alt="anntd-ae-modal-no-pay-needed-member" src="https://user-images.githubusercontent.com/673794/64205272-6c38aa00-ce4c-11e9-9797-c1e51c011668.png">

---
---

_When logged in as an admin:_
---

<img width="693" alt="member-admin-no-payment-needed" src="https://user-images.githubusercontent.com/673794/64204832-6e4e3900-ce4b-11e9-8547-9ebce95c8b81.png">

<img width="693" alt="anntd-ae-member-admin-no-payment-needed" src="https://user-images.githubusercontent.com/673794/64205267-6ba01380-ce4c-11e9-9921-1a31b84512f4.png">

---
---
---

### _Member -  Membership: Payment should be made now:_

<img width="693" alt="member-payment-needed-tooltip" src="https://user-images.githubusercontent.com/673794/64204836-6e4e3900-ce4b-11e9-9b52-c602aace84ec.png">

<img width="693" alt="anntd-ae-member-payment-needed-tooltip" src="https://user-images.githubusercontent.com/673794/64205270-6ba01380-ce4c-11e9-8ec6-653b31d2b90e.png">

---
---

### _Company -  H-Markt Branding license: No payment is due now:_

<img width="691" alt="company-no-payment-needed" src="https://user-images.githubusercontent.com/673794/64204830-6e4e3900-ce4b-11e9-8b88-7fba35e2d880.png">

<img width="691" alt="anntd-ae-company-no-payment-needed" src="https://user-images.githubusercontent.com/673794/64205265-6ba01380-ce4c-11e9-8e74-06e2d79c9ebb.png">

---
---

_Tooltip for the payment button:_
---

<img width="692" alt="anntd-ae-company-no-payment-needed-tooltip" src="https://user-images.githubusercontent.com/673794/64205264-6b077d00-ce4c-11e9-9164-1e37732cb84a.png">

---

_Modal that comes up when payment button is clicked: (In the 2nd screenshot, the underlined in red shows the words that are different from the Member membership modal above.)_
---

<img width="687" alt="modal-no-pay-needed-company" src="https://user-images.githubusercontent.com/673794/64204837-6e4e3900-ce4b-11e9-8254-028212b20500.png">

<img width="687" alt="anntd-ae-modal-no-pay-needed-company" src="https://user-images.githubusercontent.com/673794/64205271-6c38aa00-ce4c-11e9-9401-bf7e1e03442b.png">

---
---

_When logged in as an admin:_
---

<img width="691" alt="anntd-ae-company-admin-no-payment-needed" src="https://user-images.githubusercontent.com/673794/64205263-6b077d00-ce4c-11e9-9e4d-ff57b10ba0be.png">

---
---
---

### _Company -  H-Markt Branding license: Payment should be made now:_

<img width="695" alt="company-payment-needed-tooltip" src="https://user-images.githubusercontent.com/673794/64204831-6e4e3900-ce4b-11e9-8253-cd514893d0f5.png">

<img width="695" alt="anntd-ae-company-payment-needed-tooltip" src="https://user-images.githubusercontent.com/673794/64205266-6ba01380-ce4c-11e9-8b48-ec0f07118c04.png">

---

## Ready for review:
@AgileVentures/shf-project-team

2019-10-29 17:04 UTC, thesuss requested changes

2019-10-29 17:04 UTC, thesuss commented on config/locales/sv.yml
> +    no_payment_due_now: &no_payment_due_now No payment is due now.
Ingen betalning behöver göras nu.

2019-10-29 17:04 UTC, thesuss commented on config/locales/sv.yml
> +    term_paid_through: &term_paid_through Paid through
Betald till och med

2019-10-31 15:38 UTC, patmbolger reviewed
Looks great.  I didn't examine the code since it appears that one or more other PR changes are included in this (?)

2019-11-07 17:10 UTC, weedySeaDragon commented
UX approved.  I'll do the implementation in a separate PR (or PRs).   (Which is what I originally said I'd do.  I just got sooooo excited about the implementation that I started adding it to this PR. ;-) )

2019-11-07 17:10 UTC, closed without merging