show app version in simple About modal
AgileVentures/shf-project pull request #823
Opened 2020-07-16 14:28 UTC by weedySeaDragon

## PT Story: show version info in simple About box
#### PT URL: https://www.pivotaltracker.com/story/show/136308203

## Changes proposed in this pull request:
1.  simple class "AppVersion" gets info from REVISION file (created during capistrano deployment).  fallback = '1.0.0 <revision unknown>'
2.  simple "About" modal is a Bootstrap modal.  This is just a simple version; we can change/refine the design
3.  Temporary: added a footer to the layout just to have a way to display the modal.  We need to decide how to bring up the modal (where to have the link/button?)

## Screenshots (Optional):

### About modal:
<img width="358" alt="about-v1-0-sv" src="https://user-images.githubusercontent.com/673794/87682987-59158c80-c735-11ea-9ad5-423e94b25434.png">
<img width="402" alt="about-v1-0-en" src="https://user-images.githubusercontent.com/673794/87682990-59ae2300-c735-11ea-9ed7-109ecf745971.png">

---
### Footer with the link to bring up the About modal:
<img width="694" alt="about-footer" src="https://user-images.githubusercontent.com/673794/87683380-d8a35b80-c735-11ea-98c3-60de786318dd.png">

---
## Ready for review:
@AgileVentures/shf-project-team

2020-07-16 20:31 UTC, weedySeaDragon commented
FYI:  build failed with one of our common intermittently failing cucumber scenarios:
`cucumber features/view_all_companies.feature:206 # Scenario: Pagination`

but the rest passed.

2020-07-22 11:00 UTC, patmbolger commented
@weedySeaDragon This looks fine as is.  However, I recommend adding tests to the `admin` menu section of `spec/views/application/_navigation.html.haml_spec.rb`.  We're missing tests for this menu option as well as "Master Checklists", "Dashboard", and "Become this user".

2020-07-22 11:00 UTC, patmbolger requested changes
See comment.

2020-07-23 15:39 UTC, thesuss approved these changes
Approved w change

2020-07-23 15:39 UTC, thesuss commented on config/locales/sv.yml
> +    title: Om detta webbplats
Om denna webbplats

2020-07-23 21:21 UTC, merged