Fix your account on login menu
AgileVentures/shf-project pull request #841
Opened 2020-08-10 19:29 UTC by achock

## PT Story: 173278952
#### PT URL: https://www.pivotaltracker.com/n/projects/173278952

## Changes proposed in this pull request:
1. Change login menu link from my account to your account
2.
3.

## Screenshots (Optional):

---
## Ready for review:
@

2020-08-13 14:46 UTC, patmbolger commented on config/locales/en.yml
> +        your_account: Your account
This change needs to be made to the Swedish file as well (sv.yml).

2020-09-03 15:31 UTC, thesuss requested changes

2020-09-03 15:31 UTC, thesuss commented on config/locales/sv.yml
> +        your_account: Kontoen din
Ditt konto

2020-09-04 06:09 UTC, thesuss approved these changes

2020-09-04 22:05 UTC, merged