WIP Renew membership UX
AgileVentures/shf-project pull request #881
Opened 2021-01-14 16:17 UTC by weedySeaDragon

## PT Stories:  Renewals
- UX design: v1.0 of Landing page for Members  https://www.pivotaltracker.com/story/show/171403698
- Renewals must also agree to Ethical Guidelines https://www.pivotaltracker.com/story/show/172131253
- Membership Renewal: New doc required every year  https://www.pivotaltracker.com/story/show/154046321

(WIP) I'll get screenshots and more up later.

## Changes proposed in this pull request:
1. 
2.
3.

## Screenshots (Optional):

---
## Ready for review:
@

2021-01-16 17:51 UTC, patmbolger approved these changes
The views all look great to me.  Not sure what to do about the admin's users view.  Don't we have more than one additional color needed (or we need to add another column to the table) - one for "lapsed but within renewal grace period" and one for "expired, not a member (but was once a member)".   Maybe we don't care about the latter?

2021-03-11 19:57 UTC, thesuss requested changes

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      title: &upload_new_file Upload a file
Ladda upp

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      associated_with_application: "Application"
Ansökan

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      date_uploaded: "Uploaded"
Uppladdad

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      file_name: file name
filnamn

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      title_time_to_renew: "It's time to renew!"
Det är dags att förnya ditt medlemskap!

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      title_renewal_overdue: You are overdue to renew.
Ditt betaldatum har passerat

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      renewal_overdue_warning: "Your membership has lapsed! But you can still renew without resubmitting a new application. Just follow the steps below."
Du kan fortfarande förnya ditt medlemskap utan att ansöka på nytt genom att följa stegen nedan.

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      instructions: "You need to renew your membership! Here are the steps you must complete so you can keep enjoying the benefits of SHF membership:"
Nedan följer de steg du behöver göra för att fortsätta vara medlem.

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      pay_button_disabled_info: Once you have completed the steps above, you can make your payment.
När du har slutfört stegen ovan kan du betala ditt medlemskap.

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      have_been_uploaded: Files have been uploaded during your membership term
Underlag har laddats upp under medlemsperioden

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      need_to_upload: You need to upload files to show that you have continued your professional education and still meet SHF membership requirements.
Du behöver ladda upp underlag som visar att du har genomfört fortbildning under året och därmed uppfyller de krav som ställs på en medlem i Sveriges Hundföretagare.

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      upload_another: Upload another file
Ladda upp fler

2021-03-11 19:57 UTC, thesuss commented on config/locales/sv.yml
> +      title: Uploaded Files
Uppladdade filer

2021-04-08 16:46 UTC, thesuss requested changes

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +        first_day: First day
Startdatum

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +        last_day: &membership_last_day Last day
Slutdatum

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +        notes: Notes
Anteckningar:

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          current_member: Current
Aktiv medlem
(maybe?)

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          expires_soon: Expires Soon
Går ut snart

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          in_grace_period: Renewal Overdue (In Grace Period)
Gått ut (fortfarande möjlighet att förnya)

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          former_member: Former Member
Före detta medlem

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          not_a_member: Not a Member
Inte medlem

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +      changed_by_admin: "Changed by Admin %{changed_timestamp}"
Ändrad av admin %{changed_timestamp}"

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +      started_on: "Membership started on %{first_day}."
Medlemskap startat den  %{first_day}."

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +      ended_on: "Membership last day changed to %{new_last_day} and ended. Original last day was %{original_last_day}."
Medlemskap slutdatum ändrat till %{new_last_day} och avslutades. Föregående slutdatum var %{original_last_day}.

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +      last_day_changed: "Membership last day changed from %{original_last_day} to %{new_last_day}."
Slutdatum för medlemskap ändrat från %{original_last_day} till %{new_last_day}."

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +    find_co_in_my_cos: You will find the page for a company by going to the 'My Companies' menu and clicking on the company you want to see.
Du hittar sidan för ditt företag genom att gå till menyn "Mina företag" och klicka på det företag du vill se.

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +      title: "How to Edit Your Company(-ies):"
Hur du redigerar ditt/dina företag:

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +      go_to_my_cos_menu: "Once you are logged in, go to the 'My Companies' menu at the top and click on it."
Väl inloggad, leta upp "Mina företag" och klicka där.

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +      see_click_co_name: You will see all of the companies you belong to, listed by name.  Click on the Company name you want to edit.
Du kommer att se alla företag du tillhör, listade efter namn. Klicka på det företagsnamn du vill redigera.

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +      view_then_edit: You will then see the information about the company. At the bottom you will see a button to edit the company. Click it to edit the company.
Du kommer då att se information om företaget. Längst ner ser du en knapp för att redigera företaget. Klicka på den.

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +      cos_you_can_edit: "These are the companies you can edit:"
Detta är de företag du kan redigera:

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +        subject:  &subject_welcome "Tack för att du förnya ditt Sveriges Hundföretagare-medlemskap"
Tack för att du **förnyat** ditt **medlemskap i** Sveriges Hundföretagare"

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          awesome: "Awesome!"
Toppen!

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          renewed_last_day: "You have now renewed your membership. The last day of your membership is now "
Du har nu förnyat ditt medlemskap. Den sista dagen för ditt medlemskap är nu

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          companies_you_belong_to: "As a reminder, here are the companies you belong to:"
Här är det eller de företag du tillhör:

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          thanks: Thanks for joining us for another year.
Tack för att du är med ännu ett år.

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          company-incomplete: Incomplete info for company
Ofullständig information om företag

2021-04-08 16:46 UTC, thesuss commented on config/locales/sv.yml
> +          company-license-expired: H-Markt license has expired
H-märkespremien har löpt ut eller är obetald
(or is unpaid)

2021-04-18 10:04 UTC, patmbolger commented
@weedySeaDragon - great work .... I haven't reviewed the code yet but here are my first thoughts on UX.

### Status legend at bottom of users index

<img width="688" alt="status legend at bottom" src="https://user-images.githubusercontent.com/9968213/115141102-9e3e5600-a008-11eb-8b33-5194bed46342.png">

This does not seem to be needed(?).  Seems to be clutter to me.  If you retain it, probably want to add some space between that and the paginate links.

---

### "Last day" label and tooltip

<img width="555" alt="last-day label and tooltip" src="https://user-images.githubusercontent.com/9968213/115141254-389e9980-a009-11eb-8584-6343c06cee7e.png">

It would be clearer if the label, and the tooltip, referred to the last day, and expiration status, in the past tense.

---

### Uploading a file

#### File field label does not indicate allowed file size

I recommend that the file field contain a label that tells then use the max size allowed, like this:

<img width="415" alt="Screen Shot 2021-04-18 at 5 56 01 AM" src="https://user-images.githubusercontent.com/9968213/115141523-cf1f8a80-a00a-11eb-8586-19a943325ed4.png">

#### File too big - error text

<img width="693" alt="upload file - too big" src="https://user-images.githubusercontent.com/9968213/115141347-bcf11c80-a009-11eb-9fcd-9edcc2d34180.png">

I tried to upload a file that was too big - the error should show the intended file size in MB, not bytes.

#### Second attempt (after error) - file name not shown

When I selected another file after the too-big error, the file name did _not_ appear in the file field.  I wasn't sure I had actually successfully selected a file.  I saved anyway, and the file _did_ save, so it had been successfully selected.  

FWIW, here's some code that I use for that:

```
$('body').on('change', '.custom-file-input', function() {
    // Replace "Choose File" label to name of selected file, Bootstrap custom file select
    var fileName = $(this).val().split('\\').pop();
    $(this).next('.custom-file-label').addClass("selected").html(fileName);
});
```
(the field label looks like this)
```
= f.label name, label_name, class: 'custom-file-label d-inline text-truncate'
```

---

#### Uploading a file

After I successfully uploaded the file, I ended up here:

<img width="587" alt="file upload confirmation" src="https://user-images.githubusercontent.com/9968213/115141656-8ae0ba00-a00b-11eb-9de7-b0fd337abc4d.png">

I would expect it to bring me back to my account view, so I could finish renewing membership.  It hit the back arrow a couple of times to get back, and my "steps to renew" still said I needed to upload a file:

<img width="620" alt="steps to renew - after uploading file" src="https://user-images.githubusercontent.com/9968213/115141699-c3809380-a00b-11eb-94f0-73f9b9596c28.png">

I reloaded the page and that did not change.

2021-04-18 11:11 UTC, patmbolger commented
@weedySeaDragon Paperclip error messages can be a pain.  Here is some code that I use to help with making the "file size too big" message more understandable to the user:

```
def cleanup_paperclip_error_messages(file_sym, allowed_file_size_mb)
    # https://github.com/thoughtbot/paperclip/pull/1554
    errors.delete(file_sym)
    file_size_sym = (file_sym.to_s + '_file_size').to_sym
    unless errors[file_size_sym].empty?
      errors.delete(file_size_sym)
      errors[file_size_sym] << "is too big (must be #{allowed_file_size_mb} MB or smaller - your file is #{(send(file_size_sym).to_f/1000000).round(2)} MB)."
    end
  end
end

....

after_validation { cleanup_paperclip_error_messages(file_sym, allowed_file_size_mb) }
```

2021-04-27 17:08 UTC, weedySeaDragon commented
@patmbolger I'm going to address your suggestions in a separate PR,  dxcept for removing the legend at the bottom of the list of users.  That'll be in this one.
The suggestions are all about user uploading files.

2021-05-03 16:19 UTC, thesuss requested changes

2021-05-03 16:19 UTC, thesuss commented on config/locales/sv.yml
> +    how_to_upload_files: "How to Upload Files:"
Hur du laddar upp filer:

2021-05-03 16:19 UTC, thesuss commented on config/locales/sv.yml
> +    upload_files_step1: "Log in. Go the page that shows all of your uploaded files by (1) going to your login menu. Your login menu is at the far right and says '%{login_menu_title}'."
Logga in. Gå till sidan som visar alla dina uppladdade filer genom att klicka på '%{login_menu_title}'.

2021-05-03 16:19 UTC, thesuss commented on config/locales/sv.yml
> +    upload_files_step2: Click on the menu item labelled '%{uploaded_files_menu_item}'. That takes you to the page with all of your uploaded files. You can upload files there.
Klicka på menyalternativet "% {uploaded_files_menu_item}". Det tar dig till sidan med alla dina uppladdade filer. Du kan även ladda upp nya filer där.

2021-05-03 16:19 UTC, thesuss commented on config/locales/sv.yml
> +    upload_files_step3: (Your uploaded files are also listed on your account page.)
(Dina uppladdade filer listas också på din kontosida-)

2021-05-10 13:16 UTC, thesuss approved these changes

2021-05-10 15:59 UTC, merged