Show company 'complete' status to admin, members
AgileVentures/shf-project pull request #889
Opened 2021-03-11 04:24 UTC by weedySeaDragon

## PT Story: Show company 'complete' status in list of Companies, Company view
#### PT URL: https://www.pivotaltracker.com/story/show/177274707

## Changes proposed in this pull request:
1.  for admin only: display the "complete" status in the list of companies
2. for admin and company members: display the "complete" status on the company page
2. added locale entries
3.  added checkbox helpers and pre-defined icons
3.  moved all company-related features to the `features/companies` directory

## Screenshots (Optional):

### sortable column in list of Companies (index view): (only admin sees this)
<img width="859" alt="co-index-complete-col-sv" src="https://user-images.githubusercontent.com/673794/110735192-221d4b00-81de-11eb-8893-dd10aad84a6b.png">

---
---

### Company page: company information is complete (admin and company members only)
<img width="705" alt="co-show-complete-sv" src="https://user-images.githubusercontent.com/673794/110735193-22b5e180-81de-11eb-86e6-6b9f2a42e61c.png">

---
---
### Company page: company information is _not_ complete (admin and company members only)

<img width="851" alt="co-show-incomplete-en" src="https://user-images.githubusercontent.com/673794/110735194-234e7800-81de-11eb-8e15-84afaf58bd04.png">

<img width="858" alt="co-show-incomplete-sv" src="https://user-images.githubusercontent.com/673794/110735195-23e70e80-81de-11eb-8ff0-7ef4057964e1.png">

---
## Ready for review:
@thesuss @AgileVentures/shf-project-team

2021-03-11 19:42 UTC, thesuss requested changes

2021-03-11 19:42 UTC, thesuss commented on config/locales/sv.yml
> +      info_is_complete: Info komplett
Din företagssida är synlig

2021-03-11 19:42 UTC, thesuss commented on config/locales/sv.yml
> +      info_is_not_complete: Info är inte komplett
Din företagssida är inte synlig

2021-03-11 19:42 UTC, thesuss commented on config/locales/sv.yml
> +      info_is_not_complete_explanation: This company will not appear on the website until all required information is complete.
Din företagssida är bara synlig när all markerad information är angiven.

2021-03-20 20:27 UTC, patmbolger commented
I'm seeing some weird styling in the company (admin) view:

<img width="666" alt="Screen Shot 2021-03-20 at 4 13 43 PM" src="https://user-images.githubusercontent.com/9968213/111884367-aec2c880-8997-11eb-994c-dd8635ed3051.png">

Looking at `payor/_term_status.html.haml` I see content directly within rows.  Also in other areas, e.g. that file renders:

```
- if current_user.admin?
      .admin-only
        .row
          = render partial: 'payor/admin_note_and_edit_status_row',
           locals: { entity: entity,
           target_id: admin_edit_target_id,
           button_text: admin_edit_status_text }
```
and that partial contains:

```
.admin-only

  .row.mt-2
    .col.d-flex.pt-2
      .flex.pr-3
        = payment_notes_label_and_value(entity)

.row.mt-2
  .col.d-flex.pt-2.pr-3

....
```
So rows within a row.

AFAIK, only divs of class `col` should be immediate children of rows, and rows should only have `col` elements as immediate children.

2021-03-20 20:53 UTC, weedySeaDragon commented
@patmbolger  - agree.  But this is something that I haven't touched in this PR.  Can you open a new chore for that please?

2021-03-22 16:04 UTC, merged