WIP: Add default file image for no attached file
AgileVentures/shf-project pull request #928
Opened 2021-11-06 07:12 UTC by BasilMawejje

## PT Story: BUG: Possible to save a file without one attached
#### PT URL: https://www.pivotaltracker.com/story/show/180117007

## Changes proposed in this pull request:
1. Add a default file image that the Paperclip gem will show if there is actually no attached file.
2. Add a rake task that removes all nil Paperclip file objects.

## Screenshots (Optional):

---
## Ready for review:
@

2021-11-06 10:27 UTC, patmbolger reviewed
Please see comment.

2021-11-06 10:27 UTC, patmbolger commented on app/controllers/uploaded_files_controller.rb
> +      @uploaded_file = UploadedFile.new(actual_file_file_name: 'default.png')
If the user has not uploaded a file, I think we should show an error indicating that - rather than default to setting the file to a default file.

2021-11-08 16:59 UTC, patmbolger commented
@BasilMawejje There are a couple of problems with the uploaded-file-missing errors.

1) The term "Actual file" will not mean anything to the user.
2) The term we use for that file needs to also be translated to Swedish.

Right now, for EN we have:
<img width="775" alt="Screen Shot 2021-11-08 at 11 47 07 AM" src="https://user-images.githubusercontent.com/9968213/140783784-7767f675-43f1-4d25-8098-ebefd8c28e49.png">


and for SV:

<img width="781" alt="Screen Shot 2021-11-08 at 11 43 22 AM" src="https://user-images.githubusercontent.com/9968213/140783857-cf67a0e8-9dfa-47b6-bbf7-7400467be6cc.png">

If we add this last line (200) to `config/locales/en.yml`:

```
    attributes:

      uploaded_file:
        filename: &filename File name
        file_size: &file_size File size
        description: &description  Description
        actual_file: &uploaded_file Uploaded File
```

The the EN version becomes:

<img width="798" alt="Screen Shot 2021-11-08 at 11 43 45 AM" src="https://user-images.githubusercontent.com/9968213/140784984-73931307-acc5-4526-bfc9-c3fe84ff5384.png">

which will make more sense to the user.

You'll have to add an equivalent line to the SV version.  You can use google translate to provide a good guess for that, then ask @thesuss to review and correct as needed.

2021-11-09 07:14 UTC, BasilMawejje commented
Won't we need to have the translation first otherwise the feature test will fail with translation not found? 
I'm not sure the best way to work with translations on this team.

2021-11-09 09:35 UTC, patmbolger commented
> I'm not sure the best way to work with translations on this team. Do we have a wiki with regards to translations? I'd like to learn the best practices about working with them on this team.

@BasilMawejje We have this: https://github.com/AgileVentures/shf-project/wiki/How-to-Use-I18n-to-Localize-SHF

And yes, you'll need the translation in the SV locale file for the feature test to work.

2021-11-10 15:42 UTC, thesuss commented
I think there has been a misunderstanding. 
Not "require default file" 
But "require file by default"

2021-11-12 16:39 UTC, patmbolger approved these changes
Looks good!

2021-11-12 21:11 UTC, weedySeaDragon requested changes
See my comments in the files:
- suggestions in the files to change the size validation
-  different rake task needed
- feature scenario not passing for me + suggestions for changes/additional scenarios

2021-11-12 21:11 UTC, weedySeaDragon commented on lib/tasks/cleanup_nil_paperclip_files.rake
> +desc 'rake task that removes all nil Paperclip file objects'
Per the convo on Slack: Instead of this task we need a task that will **_replace these with a (valid) placeholder file._**

### Some general comments about our rake tasks:
We decided that when we have a rake task that we want to just run once, we put it into a subdirectory that represents the quarter in the year when we ran it.  That's what the folders under `lib/tasks/one_time` represent:  they are named <YYYY_Qx>  where YYYY is the year and Qx is the Quarter number.  That organizes the tasks so we can go back and see what we did, when.
So you'll want to put your task under `2021_Q4`

When we deploy with Capistrano, the file `config/deploy.rb` is used.  It's a file with the rake tasks (and supporting methods) that are run when we deploy.  If you look at the bottom of that file, you can see the sequence (hooks/callbacks) of our custom tasks that Capistrano runs when we deploy.  
One of the things that happens is that any _one time_ task rake files that haven't yet been run are run.  Once they're run, it's recorded in the db and the `.rake` file is renamed to `.rake.ran`.

_(As I write this, I realize this should really be in the wiki.  I'll copy and paste this write up into it if it's not already there.)_

And no need to start a description with "rake task...." That's kind of redundant. :-)

2021-11-12 21:11 UTC, weedySeaDragon commented on app/models/uploaded_file.rb
> +                       }, presence: true
Another way to do this is:
```
size: { in: 1..5000000.bytes,
                               message: :file_too_large
                       }
```
I _think_ this would be preferable, because it prohibits empty files.
It may be that we want both to validate for `presence` and a way to ensure that size > 0.

2021-11-12 21:11 UTC, weedySeaDragon commented on spec/models/uploaded_file_spec.rb
>    end
We should specify that the file size must be > 0.  something like:
```

    it 'file size 0 is invalid' do
      Tempfile.create('tempfile-empty.png') do |empty_file|
        expect(build(:uploaded_file, actual_file: empty_file)).not_to be_valid
      end
    end

    it 'file size > 0 is valid' do
      expect(build(:uploaded_file, :png)).to be_valid
    end
```
I'll leave it to you to decide where to put those (how to organize).  

_However_ when I add those tests, the `it { should validate_presence_of(:actual_file) }` test gives me a problem.  ("Expected UploadedFile to validate that :actual_file cannot be
empty/falsy, but this could not be proved. ...")

This means we need to think about both what the test is trying to do (and failing) and whether my idea about checking the file size > 0 is reasonable or not.

2021-11-12 21:11 UTC, weedySeaDragon commented on features/uploaded-files/member-uploads-files.feature
> +  Scenario: Member tries to save without specifying upload file
This scenario is failing for me.

2021-11-12 21:11 UTC, weedySeaDragon commented on features/uploaded-files/member-uploads-files.feature
> +    Then I should see t("model_errors.one")
I think the right thing to do is to disable the save/submit button if no file has been uploaded. So this scenario should be something like:
 When I am on the "upload a new file" page
 Then the link button t("save") should be disabled
 (then after I upload a file, Then the link button t("save") should not be disabled

We should have a scenario where a user tries to upload a file that is empty (size == 0).  (That scenario should go into the `size_validation.feature` file. And the `size_validation.feature` file should be moved into the `features/uploaded-files` directory.)

2022-01-12 17:33 UTC, merged