[WIP] Bugfix  add delete to Edit Membership Application for admin
AgileVentures/shf-project pull request #96
Opened 2016-12-19 22:12 UTC by weedySeaDragon

WIP!
(@thesuss -- could you fill this out?  it'd help me.)

PT Story: 

Changes proposed in this pull request:
1. 
2.
3.

Screenshots (Optional):

Ready for review:
@

2016-12-19 22:18 UTC, thesuss commented on app/views/membership_applications/edit.html.haml
> +      = link_to "#{t('.delete')}", @membership_application, method: :delete, data: { :confirm => "#{t('.confirm_are_you_sure')}" }
was it { confirm: "#{t('.confirm_are_you_sure')}" that didnt work?

2016-12-19 22:30 UTC, thesuss commented on app/views/membership_applications/edit.html.haml
> +      = link_to "#{t('.delete')}", @membership_application, method: :delete, data: { :confirm => "#{t('.confirm_are_you_sure')}" }
data: { confirm: "#{t('.confirm_are_you_sure')}" } 
should work

2016-12-20 01:11 UTC, weedySeaDragon commented on features/step_definitions/membership_application_steps.rb
> +Given(/^I am on (the show )+"([^"]*)" application page$/) do |optional, first_name|
I know, houndbot.  But it's a regular expression and I don't know how to deal with it any better than that right now.

2016-12-20 06:43 UTC, thesuss commented
I'll check this at breakfast break :)

2016-12-20 19:36 UTC, patmbolger reviewed
Reviewed .... please see comments.

2016-12-20 19:36 UTC, patmbolger commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
Do we need the full URL path or can we get away with a relative path (that is, use `membership_applications_url`)?

2016-12-20 19:36 UTC, patmbolger commented on app/policies/application_policy.rb
> +    is_admin? ||  @record.user == @user
We could also just do `@user&.is_admin?` and dispense with the helper method.

(similarly for other policy files with the same helper method)

2016-12-20 19:36 UTC, patmbolger commented on app/policies/application_policy.rb
> +    is_admin? ||  @record.user == @user
Also, I notice that we have inconsistent instance var references in our policy files - that is, in some we refer to `@user` (like this one) and others we use the reader method `user` (like in `membership_application_policy.rb`).

We should be consistent in these references - I suggest the reader methods be used.

2016-12-20 19:53 UTC, weedySeaDragon commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
You should use URLs with `redirect_to` : http://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_to

The general guideline is:  `_url` in controllers (think: server side),` _path` in views (think: browser side)

2016-12-20 19:54 UTC, weedySeaDragon commented on app/policies/application_policy.rb
> +    is_admin? ||  @record.user == @user
totally agree. policies need cleaning up/refactoring.  we have a chore about refactoring MembershipApplicationPolicy, but we really do need to do all of them.  I'll make one.

2016-12-21 23:21 UTC, patmbolger requested changes
Review - please see additional comment.

2016-12-21 23:21 UTC, patmbolger commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
I noticed that the english wording (in yml file) for this is: ```Application deleted.```, yet the Swedish is ```Ansökan raderad.``` - which is plural ("Applications deleted.") and should be singular.

May want to fix in this PR, as it affects new tests in this PR.

2016-12-21 23:37 UTC, weedySeaDragon commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
(changed my mind again again.)

I'll fix it.

2016-12-22 00:42 UTC, weedySeaDragon commented
suddenly, the build is failing here, but passing on my local system.  
So I'm reverting until I can get back to a passing build. (I suspect it's the automatic merge done by github)

2016-12-22 01:07 UTC, weedySeaDragon commented
Not entirely sure what was going on with my local branch vs. GH.  But it's passing.

ready for another review @patmbolger

2016-12-22 06:28 UTC, thesuss commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
None of them are plural

2016-12-22 06:31 UTC, thesuss commented
There is an intermittent error in the build. That's why I pushed for the refactoring as prioritized.

2016-12-22 06:49 UTC, weedySeaDragon commented
Which branch did you first see the intermittent error?  
I wouldn't describe the build error that I got here as 'intermittent' -- it was definitely consistent.  So (as you can all see), I reverted my commits and re-did the changes.  I left off moving the info in the locale files.  (Plus I was tired and needed to take a break.)

Yes -- definitely time to refactor and clean up.  (Even if we didn't have intermittent errors, it's needed.)

2016-12-22 06:51 UTC, weedySeaDragon commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
We can fix the locale files for that in a tiny PR after we get all of the sections completed with the PivT feature https://www.pivotaltracker.com/story/show/133316647

I'd really like to get the feature done -- touching all of the models, controllers, features, locale files.   :-)

2016-12-22 09:47 UTC, thesuss commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
I don't know why @patmbolger trusts Google translate over me?

2016-12-22 09:59 UTC, weedySeaDragon commented
ready for review (finally) @patmbolger 
(figured out that the intermittent failing was due to the wrong db_cleaning strategy being used for cucumber tests.  I changed that: should have been _truncation_).

Susanna can make sure the text is right in the locale files in another PR if needed.  Now the infrastructure is there _and_ the features and controller are using the t() as appropriate.

2016-12-22 10:34 UTC, patmbolger commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
@thesuss - I *don't* trust google translate (GT) over you - it's just that it is the only way I can test English-to-Swedish translations.

Your judgement is the only one that counts :)

2016-12-22 10:42 UTC, thesuss commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
The swedish was there (hardcoded in the views/messages), its the english that is added

2016-12-22 10:53 UTC, patmbolger commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
@thesuss  - yes, indeed .... and so I will focus on checking the swedish-to-english translations.

In this case, google translate is wrong.

However, it looks like rails i18n implementation is smarter than GT.  When I run this branch on my machine (who locale == english), the translated flash message is correct:

<img width="420" alt="screen shot 2016-12-22 at 5 50 37 am" src="https://cloud.githubusercontent.com/assets/9968213/21423354/a1e5eeec-c80a-11e6-9ae6-556cda5b0eb3.png">

2016-12-22 10:56 UTC, thesuss commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
Yes, but it was the swedish one you said something about, is that still correct?
Answer is no:
`application_deleted: Ansökan raderat.`
It was correct, thus should be
`application_deleted: Ansökan raderad.`

2016-12-22 10:57 UTC, thesuss commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
But, that could be fixed separately, if someone *hint* puts it in piv.

2016-12-22 11:01 UTC, patmbolger approved these changes
PR looks good.

2016-12-22 11:14 UTC, merged

2016-12-22 12:31 UTC, patmbolger commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
Not sure I follow this comment ... do we need to change the translation?  But, you say "it was correct ..." so I'm not sure what is meant here.

2016-12-22 13:19 UTC, thesuss commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
it *WAS* correct, when you added this comment. Then Ashley changed it. Now it is not correct. =) 
it is (now)
`application_deleted: Ansökan raderat.`
It was, and should be
`application_deleted: Ansökan raderad.`

2016-12-22 13:20 UTC, thesuss commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
I added it here: https://www.pivotaltracker.com/story/show/133316647

2016-12-22 13:21 UTC, patmbolger commented on app/controllers/membership_applications_controller.rb
> +    redirect_to membership_applications_url, notice: t('membership_applications.application_deleted')
@weedySeaDragon - do you want to und your change to fix this in this PR?